trustbloc/wallet

- cmd/user-agent/src/pages/Connections.vue
This PR includes:
*  Register/Unregister the router (form on UI)
* allows accepting the invitation (button on UI)
* allows accepting the exchange request (button on UI)
NOTE: need to deploy a router
> feat: DidExchange allows establishing did-connection through the router

- cmd/user-agent/src/pages/PageNotFound.vue
Adds license header for PageNotFound.
> fix: Adds license header

- cmd/user-agent/src/pages/DIDManagement.vue
- cmd/user-agent/src/pages/chapi/Login.vue
- cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
- cmd/user-agent/src/pages/chapi/wallet/common/keyValStore.js
- cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
- cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
- cmd/user-agent/src/pages/chapi/wallet/index.js
- cmd/user-agent/src/pages/chapi/wallet/register/register.js
- cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
- webwallet login will register wallet and assign a DID for each login
- webwallet logout will unregister and removed wallet user entry from db
- webwallet get by credential query will use wallet user did for signing
presentation
- For now, DID auth will still continue to use created DIDs from DID
management.
- Closes #187
> feat: web wallet login/logout/register/uniregister

- cmd/user-agent/src/pages/WebWallet.vue
- cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
- cmd/user-agent/src/pages/chapi/wallet/common/util.js
- cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
- test/user-agent/test/presentationDefQuery/presentationDef.spec.js
- test/user-agent/test/presentationDefQuery/testdata.js
- added feature of fallback search to manifest VC, when a descriptor
fails to find matches it will go through manifest VCs
- did connect request can have manifest VCs along with invitation
- TODO: result VC to have details enough to establish did comm between
RP & Issuer for fetching VCs dynamically
- Closes #211
> feat: webwallet manifest VC and presentation location

- cmd/user-agent/src/components/SidebarPlugin/SideBar.vue
- cmd/user-agent/src/main.js
- cmd/user-agent/src/pages/Layout/DashboardLayout.vue
Added `dev mode` support. Now, we have a button to switch between modes. Switching between modes triggers an event. So, we can listen to events and draw stuff according to the chosen mode.
Screens:
> feat: Added dev mode

- .gitignore
- cmd/http-server/startcmd/start.go
- cmd/http-server/startcmd/start_test.go
- cmd/trustbloc-agent-js-worker/go.sum
- cmd/trustbloc-agent-js-worker/main.go
- cmd/trustbloc-agent-js-worker/src/trustblocagent.js
- cmd/user-agent/src/main.js
- cmd/user-agent/src/pages/DIDManagement.vue
- cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
- cmd/user-agent/src/pages/chapi/wallet/register/register.js
- cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
- docs/test/test.md
- go.mod
- go.sum
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/command/sdscomm/sdscomm.go
- pkg/controller/command/sdscomm/sdscomm_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- test/bdd/fixtures/agent-wasm/.env
- test/bdd/fixtures/agent-wasm/docker-compose.yml
- test/user-agent/test/common.js
closes #245, closes #269
- The "make user-agent-start" target now starts up an SDS and CouchDB instance
- DIDs are now stored in SDS (in plaintext) in addition to local browser storage
> feat: Plaintext DID storage in SDS

- cmd/user-agent/package.json
- test/bdd/fixtures/agent-wasm/.env
- test/user-agent/package.json
Now, when the user accepts the request, a friendly name will be displayed instead of did id.
> feat: Newer aries snapshot (label instead of did id)

- cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
- test/user-agent/test/presentationDefQuery/presentationDef.spec.js
- test/user-agent/test/presentationDefQuery/testdata.js
This change is really more of a temporary (and cheap) solution to support [this](https://github.com/trustbloc/edge-adapter/pull/252) change in the RP edge-adapter.
I say this is *temporary* because I think a better solution would be to extend the [IssuerManifestCredential](https://github.com/trustbloc/context/blob/master/vc/issuer-manifest-credential-v1.jsonld) such that `contexts` is an array of VCs or VC-like objects against which the wallet and Issuer can evaluate the presentation-exchange criteria. This change would align better with [this existing TODO](https://github.com/trustbloc/edge-agent/blob/5b8834b8fe1ac848080f81b3c27ef46d22e65877/cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js#L208).
> feat: issuer manifest is matched if the credential schema uri is specified in a `const` filter

- cmd/user-agent/src/main.js
- pkg/controller/command/didclient/command.go
- pkg/controller/command/didclient/command_test.go
- pkg/controller/command/sdscomm/sdscomm.go
- pkg/controller/command/sdscomm/sdscomm_test.go
closes #296
- user-agent JavaScript code can now be run with "npm run serve" without SDS-related runtime errors.
- Added blank SDS URL check to sdscomm. This prevents an unintuitive error message from being produced.
- Added blank agent username check to sdscomm.
> fix: Added default SDS URL and agent username TrustBloc agent opts

- cmd/user-agent/src/store/modules/credentials.js
Filters associated credentials with null or missing labels.
> fix: Filters credential with an empty label

- cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
- cmd/user-agent/src/pages/chapi/wallet/common/util.js
- cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
- in current implemnentation we show local and remote(didcomm)
credentials in same list in UI while getting consent from user.
- after this change, issuers who can issue credentials over didcomm will
be listed seprately and UI will show different messages for user
consent.
- closes #317
> feat: webwallet get user consent for sharing credentials over DIDComm

- cmd/user-agent/src/main.js
- cmd/user-agent/src/pages/Layout/TopNavbar.vue
- cmd/user-agent/src/pages/chapi/BlockNoAuth.vue
- cmd/user-agent/src/pages/chapi/DIDConnect.vue
- cmd/user-agent/src/pages/chapi/Login.vue
- cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
- cmd/user-agent/src/pages/chapi/wallet/register/register.js
- cmd/user-agent/src/router/index.js
- securing CHAPI pages from acessing without auth
- login redirect made dynamic, can be applied to any page, not just
dashboard
- fixed logout issue where CHAPI polyfill wasn't getting unregistered.
- Closes #342
- Closes #343
> feat: block access to CHAPI iframe for invalid session

- cmd/user-agent/src/main.js
- cmd/user-agent/src/pages/Connections.vue
- cmd/user-agent/src/pages/DIDManagement.vue
- cmd/user-agent/src/pages/Dashboard.vue
- cmd/user-agent/src/pages/IssueCredential.vue
- cmd/user-agent/src/pages/PresentProof.vue
- cmd/user-agent/src/pages/TablePresentation.vue
- cmd/user-agent/src/pages/WebWallet.vue
- cmd/user-agent/src/pages/chapi/DIDAuth.vue
- cmd/user-agent/src/pages/chapi/DIDConnect.vue
- cmd/user-agent/src/pages/chapi/GetCredentials.vue
- cmd/user-agent/src/pages/chapi/Logout.vue
- cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
- cmd/user-agent/src/pages/chapi/Store.vue
- cmd/user-agent/src/router/index.js
- cmd/user-agent/src/store/modules/connections.js
- cmd/user-agent/src/store/modules/credentials.js
- cmd/user-agent/src/store/modules/init.js
- cmd/user-agent/src/store/modules/mediator.js
- cmd/user-agent/src/store/modules/presentation.js
- cmd/user-agent/src/store/modules/user.js
- no more 'window.$aries', demos pages will reuse webwallet aries
instance
- improved CHAPI window performance by moving major demo pages related (non CHAPI) 
'loading/initialization' to respective vue modules.
- many more refactoring
- closes #352 
> feat: user agent wallet demos to reuse webwallet user aries

- cmd/http-server/startcmd/start.go
- pkg/restapi/common/oidc/client.go
- pkg/restapi/common/oidc/client_test.go
- pkg/restapi/oidc/dependencies.go
- pkg/restapi/oidc/helper.go
- pkg/restapi/oidc/operations.go
- pkg/restapi/oidc/operations_test.go
- pkg/restapi/oidc/persistedData.go
closes #375
This PR provides a skeleton for the OIDC callback endpoint. There are still additional things to do (some of them figured out, some of them are pending final design decisions).
* added a new OIDC `/callback` endpoint
* created a new OIDC client to hide all that complexity. Refactored existing code in the REST operations to use this client
* added new `user` and `tokens` stores to the OIDC REST operations
> feat: #375 OIDC callback endpoint

- cmd/http-server/go.sum
- cmd/http-server/startcmd/start.go
- cmd/http-server/startcmd/start_test.go
- cmd/trustbloc-agent-js-worker/go.sum
- go.mod
- go.sum
- pkg/restapi/common/common.go
- pkg/restapi/oidc/dependencies.go
- pkg/restapi/oidc/helper.go
- pkg/restapi/oidc/operations.go
- pkg/restapi/oidc/operations_test.go
- scripts/generate_test_keys.sh
- test/bdd/fixtures/.gitignore
- test/bdd/fixtures/agent-wasm/docker-compose.yml
- test/user-agent/package-lock.json
closes #379 
This patch adds initial support for user session cookies. The OAuth2 'state' parameter is stored in an encrypted and authenticated form in a session cookie that is then validated against the value received in the 'state' query parameter in the callback.
We use the gorilla/sessions module that allows setting an authentication key and an encryption key in order to authenticate and protect the session cookies stored in the browser. These keys are configured as "session cookie keys" and passed in by an admin as variables that point to a file that contains the raw bytes.
> feat: #379 session cookies

- test/user-agent/test/mocks/adapters/issuerAdapter.js
- test/user-agent/test/mocks/index.js
- test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
- test/user-agent/test/wallet/walletCredentialQuery.spec.js
- moved issuer & RP logic in JS bddtests to dedicated adapters, so that
test code contains only wallet related logics
- Part of #425
> refactor: webwallet js bddtests - issuer and rp adapter mocks

- pkg/restapi/oidc/operations.go
- pkg/restapi/oidc/operations_test.go
Check the user's session cookie before redirecting to the OIDC.
Closes #497 
> fix: Check the user's session cookie before redirecting to the OIDC

- cmd/wallet-web/src/store/modules/options.js
- cmd/wallet-web/src/store/modules/user.js
A temporary workaround to allow the user's EDV vault ID to be accessed from a CHAPI window.
> feat: EDV vault ID storage workaround

- cmd/wallet-web/package-lock.json
- cmd/wallet-web/package.json
- cmd/wallet-web/src/events/index.js
- cmd/wallet-web/src/pages/chapi/wallet/common/messaging.js
- test/wallet-web/package.json
- Also increased timeout values. This is a temporary change and will be decreased back down to a more reasonable value in a future commit.
> feat: Update agent-sdk version

- cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
- cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
- This is a temporary change and will be decreased back down to a more reasonable value in a future commit once EDV server storage speed is improved.
> fix: Increase timeout to accommodate slow EDV server

- cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
This is a temporary change and will be decreased back down to a more reasonable value in a future commit once EDV server storage speed is improved.
> fix: Increase get credential retries to accommodate slow EDV server

- test/bdd/fixtures/wallet-web/.env
- test/bdd/fixtures/wallet-web/docker-compose.yml
- test/bdd/go.mod
- test/bdd/go.sum
This PR **does not** enable ZCAPLD authorization on hub-kms. ZCAPLD authz will be enabled in #543 .
Changes:
* hub-kms: support zcapld authorization https://github.com/trustbloc/hub-kms/pull/108
* go mod tidy
> chore: update hub-kms image

- pkg/restapi/oidc/operations.go
- test/bdd/fixtures/wallet-web/docker-compose.yml
- test/bdd/fixtures/wallet-web/oathkeeper-config/auth-keyserver/config.yaml
- test/bdd/fixtures/wallet-web/oathkeeper-config/auth-keyserver/rules/resource-server.json
- test/bdd/fixtures/wallet-web/oathkeeper-config/ops-keyserver/config.yaml
- test/bdd/fixtures/wallet-web/oathkeeper-config/ops-keyserver/rules/resource-server.json
:warning: **this will break edge-agent in the sandbox until PR trustbloc/edge-sandbox#681 is merged** :warning: 
Oathkeeper expects the token in plain form instead of base64-encoding as per https://tools.ietf.org/html/rfc6750#section-2.1.
> refactor: bearer token usage for hub-kms/oathkeeper

- cmd/wallet-server/go.sum
- cmd/wallet-web/package-lock.json
- cmd/wallet-web/package.json
- cmd/wallet-web/src/store/modules/options.js
- docs/test/test.md
- go.mod
- go.sum
- pkg/restapi/oidc/models.go
- pkg/restapi/oidc/operations.go
- pkg/restapi/oidc/operations_test.go
- pkg/restapi/oidc/webkms.go
- test/bdd/fixtures/wallet-web/.env
- test/bdd/fixtures/wallet-web/docker-compose.yml
- test/bdd/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/config.yaml
- test/bdd/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/config.yaml
- test/bdd/go.sum
- test/wallet-web/package-lock.json
- test/wallet-web/package.json
closes #546
closes #580 
----
blocked by:
-----
changes:
* use KMS capability for OPS keyserver operations
* update hub-kms image in tests/demo
* enable zcaps authz for hub-kms in tests/demo
* **temporarily sending access_token and ops keyserver zcap to the frontend to enable both key servers to be used there** (see TODO #583 )
> fix: use KMS capability for OPS keyserver operations

- cmd/wallet-web/src/pages/chapi/Login.vue
The changes in the PR https://github.com/trustbloc/edge-agent/pull/597/files#diff-3c022876e10a283b7ec65cfcdc50551303c25d2db0d028ff3db285e903580a85R137-R148 broke the CHAPI window UI screens as the class names were conflicting. Updated the class name to be different from the existing ones
> fix: UI alignment fix

- cmd/wallet-web/package.json
- cmd/wallet-web/src/store/modules/options.js
- test/bdd/fixtures/wallet-web/docker-compose.yml
- test/bdd/fixtures/wallet-web/hydra-config/demo_auth-rest-hydra_configure.sh
- test/bdd/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/config.yaml
- test/bdd/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/config.yaml
Allows using `make wallet-web-dev-start` target for local development.
NOTE: All images should be already built. If you need to build them use `make wallet-web-start`
> feat: Allows using wallet-web-dev-start target for local development

- cmd/wallet-web/src/pages/chapi/wallet/common/didExchange.js
- cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
- cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
- test/wallet-web/test/mocks/adapters/issuerAdapter.js
- RP will wait for state complete message before proceeding with blinded
routing steps.
- this will save few cycles since this one removes need for having retry
on did doc request.
- closes #611
> feat: wallet didconnect - wait for state complete message

- test/wallet-web/package-lock.json
following the latest agent-sdk revision update, the lock file was missing this update as well
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>
> chore: update package-lock.json with latest agent-sdk revision

- cmd/wallet-web/src/pages/chapi/wallet/didmgmt/didManager.js
This PR updates code so the creation of keys for Trustbloc DID is done in parallel. This cuts around 1s from "assign DID" part of "Sign Up" flow.
> perf: create keys for Trustbloc DID in parallel

- test/bdd/fixtures/wallet-web/.env
The EDV Docker image was accidentally rolled back to an older version in a previous commit. This updates it to the correct, latest version.
> fix: EDV Docker image version

- cmd/wallet-server/go.mod
- cmd/wallet-server/go.sum
- cmd/wallet-server/startcmd/agentconfig.go
- cmd/wallet-server/startcmd/start.go
- cmd/wallet-server/startcmd/start_test.go
It was removed in a previous commit since the new LevelDB implementation wasn't ready yet, but it is now.
> feat: Re-add LevelDB option for wallet-server

- cmd/wallet-web/src/pages/chapi/Login.vue
Fixes #752
Adjusted home page alignment on medium breakpoint and above:
Signed-off-by: Anton Biriukov anton.biriukov@securekey.com
> fix: adjusted container alignment

- cmd/wallet-web/package-lock.json
- cmd/wallet-web/package.json
- docs/test/test.md
Removed the fiber 
Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.
> chore: Update to npm 7 and recent agent-sdk-web version

- cmd/wallet-web/src/assets/img/demo_provider.svg
- cmd/wallet-web/src/pages/chapi/Signup.vue
- Fixed the divider length 
- Add demo provider icon 
- Moved sign up button alignment as per the new screem 
- Removed beat loader 
> feat: Remove beat loader and add demo-provider icon and updated ui

- cmd/wallet-web/package-lock.json
- cmd/wallet-web/package.json
- cmd/wallet-web/src/pages/DIDManagement.vue
- cmd/wallet-web/src/pages/mixins/common/helper.js
- added feature to modify verification method in wallet preferences
- Part of #814
Added Granular control over user preferences like DID, verification method & signature type to use for generating proofs from wallet.
> feat: enhancement in wallet preference updates

- cmd/wallet-web/src/assets/img/onboarding-bg-sm.svg
- cmd/wallet-web/src/components/Spinner/Spinner.vue
- cmd/wallet-web/src/pages/Signin.vue
- cmd/wallet-web/src/pages/layout/ContentFooter.vue
- cmd/wallet-web/src/router/index.js
- cmd/wallet-web/tailwind.js
Related to #835 
Implemented new Sign In page according to [the designs](https://share.goabstract.com/74bf341b-17d6-44a2-bf81-6246608b5d73?collectionLayerId=503aa34c-10e9-4d8b-98de-309e5e9d3407&mode=design). Adjusted Sign Up screen, added new tailwind spinner, adjusted footer and layout.
https://user-images.githubusercontent.com/33902374/126247044-9db77794-22bb-47d6-9f4a-3966f68c79c0.mov
> feat: implemented new sign in screen

- cmd/wallet-web/src/assets/img/home_wallet.png
- cmd/wallet-web/src/pages/Login.vue
- cmd/wallet-web/src/pages/Signin.vue
- cmd/wallet-web/src/pages/Signup.vue
- cmd/wallet-web/tailwind.js
Fixes #861
Removed the image containing the old logo. This page will be switched with the new Sign in page.
> chore: removed image containing old logo

- cmd/wallet-web/src/pages/Signup.vue
Aries agent init aborted due to window open command. Logic needs to be revisited during sign-up pop-up feat implementation
> fix: sign-up remove window open line

- cmd/wallet-web/src/assets/img/close-icon.svg
- cmd/wallet-web/src/assets/img/triangle-exclamation.svg
- cmd/wallet-web/src/components/ToastNotification/ToastNotification.vue
- cmd/wallet-web/src/main.js
- cmd/wallet-web/src/translations/en.json
- cmd/wallet-web/src/translations/fr.json
- cmd/wallet-web/tailwind.js
closes #768
Alert can be used in this style anywhere in the wallet vue component`<toast-notification
:title="i18n.Signup.errorToast.title"
:description="i18n.Signup.errorToast.description"
type="error"></toast-notification>`
Integration will be done in #898 
This is the custom resusable toast component, which can be used anywhere in the wallet in the following style.  We are only supporting error type. 
> feat: Add reusable Toast Component 

- cmd/wallet-web/src/pages/LoginHandle.vue
- cmd/wallet-web/src/pages/Signin.vue
- cmd/wallet-web/src/pages/Signup.vue
- cmd/wallet-web/src/store/index.js
- cmd/wallet-web/src/store/modules/user.js
- cmd/wallet-web/src/translations/en.json
- cmd/wallet-web/src/translations/fr.json
The toast notification is tested with adding wrong param in option.js file to simulate system failure. 
One existing issue. Pop up it self removes the loader if user closes the window while its redirecting, but when its redirected, the third party then loader dont get removed. I havent found a way where window.listener can unload from window.location.href.  Issue #914 is created for that
https://user-images.githubusercontent.com/7862595/128655697-8331f83c-6dab-4cf3-ac6c-59d2c026ff80.mov
closes #899 
closes #898
> feat: Integrate toast notification for system failures and remove loader on closed popup

- cmd/wallet-web/src/components/LocaleSwitcher/LocaleSwitcher.vue
- cmd/wallet-web/src/components/Logo/Logo.vue
- cmd/wallet-web/src/components/SidebarPlugin/Sidebar.vue
- cmd/wallet-web/src/components/SidebarPlugin/SidebarLink.vue
- cmd/wallet-web/src/components/Signout/Signout.vue
- cmd/wallet-web/src/pages/Signin.vue
- cmd/wallet-web/src/pages/Signup.vue
- cmd/wallet-web/src/pages/layout/Header.vue
- cmd/wallet-web/tailwind.js
Fixes #965
I also removed link from the `Logo` component as it should not be clickable per designs.
> feat: added focus styles to sidebar links

- cmd/wallet-web/src/config/credentialDisplayData.js
- cmd/wallet-web/src/pages/CredentialDetails.vue
- cmd/wallet-web/src/store/modules/user.js
closes #1035  #1032 
1. On page refresh now the credential detail screen works as well. 
2 If the type is image it will render as image otherwise just simple value. 
3. Rearranged the credential detail config in the sequence to display
https://user-images.githubusercontent.com/7862595/132260060-921319b7-adfe-47e6-892e-6f1035b3b471.mov
> fix: Credential detail on refresh fails to get processed credential and render base64 image

- cmd/wallet-web/package-lock.json
- cmd/wallet-web/package.json
Since, there are code breaking changes in agent-sdk, we need to set their version to a fixed snapshot/release
> chore: set agent-sdk and wallet-sdk to fixed version

- cmd/wallet-web/src/pages/DIDAuth.vue
This is a temp solution and the root cause will be tracked as part of https://github.com/trustbloc/wallet/issues/1067.
closes #1066 
> fix: disable error display for DIDAuth query failure

- cmd/wallet-web/src/components/Navbar/NavbarLink.vue
- cmd/wallet-web/src/components/Signout/Signout.vue
- cmd/wallet-web/src/pages/Signin.vue
- cmd/wallet-web/src/pages/Signup.vue
Fixes #1143
This would allow to click on these elements by pressing `enter` key when focused.
> feat: added on key enter even handler for some ui elements

- cmd/wallet-web/src/pages/mixins/common/helper.js
Fixes #1235
This PR replaces `Base64.encode()` with `Base64.encodeURI()` to ensure base64-url encoding. The `Base64.decode()` function is universal and works with both `base64` and `base64-url`-encoded strings, so we do not need to touch it.
> fix: use base64url encoding for credential id

- test/mock/adapter/templates/css/tailwind.css
- test/mock/adapter/templates/webWallet.html
- test/mock/demo-login-consent-server/main.go
- test/mock/demo-login-consent-server/templates/bankconsent.html
- test/mock/demo-login-consent-server/templates/banklogin.html
- test/mock/demo-login-consent-server/templates/consent.html
- test/mock/demo-login-consent-server/templates/css/tailwind.css
- test/mock/demo-login-consent-server/templates/login.html
- test/mock/demo-login-consent-server/templates/uploadCred.html
- test/mock/demo-login-consent-server/templates/uploadCredConsent.html
Fixes #1312
Our demo login page now uses tailwindcss styles generated from our theme. Updating the rest of the demo pages would take sufficient amount of time, because they were not implemented with our theme and lots of colors that are currently in use there do not exist in our theme. Updated default tailwindcss imports for those pages instead.
> fix: updated tailwind imports in mock test pages

- cmd/wallet-web/src/components/InputField/InputField.vue
- cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
- cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
Fixes #1309 
https://user-images.githubusercontent.com/33902374/146252142-fb9e62e1-f94c-4fdb-b9c1-b117e7d1146c.mov
> feat: added loading state, auto refresh to add and delete vault modals

- cmd/wallet-web/src/pages/Signin.vue
- cmd/wallet-web/src/pages/Signup.vue
> fix: Loading spinner is not centered in the authentication providers 

- scripts/run_ui_automation.sh
- test/ui-automation/wdio.conf.js
wallet name is not displayed in CHAPI window in latest chrom
> fix: update CHAPI wallet name to wallet url

- test/mock/adapter/adapter.go
- test/mock/adapter/templates/issuer/issuer.html
- test/mock/adapter/templates/issuer/waci-issuer.html
- test/mock/adapter/templates/verifier/oidc-verifier.html
- test/mock/adapter/templates/verifier/verifier.html
- test/mock/adapter/templates/verifier/waci-verifier.html
- test/ui-automation/test/specs/credential-interaction-flow.js
- test/ui-automation/test/specs/waci-flow.js
- test/ui-automation/wdio.conf.js
- Added a issuer/verifier home page to direct users to different type of flows (waci, oidc, etc)
- Update waci demo button names
- Add oidc share flow TODO page
refactor to support new flows like #1529
> test: update mock issuer/verifier to support different type of flows

- test/mock/adapter/adapter.go
- test/mock/adapter/templates/verifier/oidc-verifier.html
https://user-images.githubusercontent.com/10111768/159350564-749349e0-e266-4a8d-8923-01b4c930219e.mov
closes #1585 
> test: [oidc4vp] display success/error message, id_token and vp_token

- cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
- cmd/wallet-web/src/components/CredentialDetails/RenameCredentialModal.vue
- cmd/wallet-web/src/components/InputField/InputField.vue
- cmd/wallet-web/src/components/Modal/Modal.vue
- cmd/wallet-web/src/components/WACI/CredentialOverview.vue
- cmd/wallet-web/src/pages/CredentialDetails.vue
- cmd/wallet-web/src/pages/Credentials.vue
- cmd/wallet-web/src/pages/Vaults.vue
- cmd/wallet-web/src/pages/WACIIssue.vue
- cmd/wallet-web/src/pages/WACIShare.vue
- cmd/wallet-web/src/translations/CredentialDetails/en.json
- cmd/wallet-web/src/translations/CredentialDetails/fr.json
partof #1516
- Regarding validation as discussed with UX team, As long as there is a way for the user to differentiate credentials we dont have a problem. Either by different look, or by different name. Therefore removing same name validation for now as discussed with the team
https://user-images.githubusercontent.com/7862595/159482503-3647db06-06d7-4dcb-bff5-da24f29bed3c.mov
Updated video
https://user-images.githubusercontent.com/7862595/159603351-dce1f619-c57e-4de4-a37a-b62e091cda15.mp4
- Fixed -> - Fixed when the modal is opened it should show the existing name as a placeholder text. 
- When entering the new valid name the bottom border of the input field is not red now 
-
> feat: Implement rename credential change

- cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
There was one component I missed and did not add the `Component` suffix to from the[ last PR](https://github.com/trustbloc/wallet/pull/1668) for renaming Vue components to be multi-worded. (sorry about that!) 
This PR fixes that and also I verified that all the other components have the `Component` suffix.
> fix: rename Vue components to have multi-worded names 

- cmd/wallet-web/src/components/CredentialPreview/CredentialPreviewComponent.vue
Closes #1597 : Changed `CredentialPreviewComponent` to use `css` instead of `tailwindcss` for focus style 
Before (light blue focus ring on credentials that are not white)         |  After
:-------------------------:|:-------------------------:
> fix: apply dynamic focus styles to credential previews

- cmd/wallet-web/src/config/gnap-access-token.json
- cmd/wallet-web/src/mixins/gnap/gnap.js
- cmd/wallet-web/src/router/index.js
- cmd/wallet-web/src/store/modules/options.js
- test/fixtures/wallet-web/.env
- test/fixtures/wallet-web/static/config/gnap-access-token.json
closes #1709
I get 401 error which is expected until http signer is in ERROR access policy failed to handle access request: client request verification failure: request with body should have a content-digest header
> feat: Prepare valid gnap request to access agent sdk request access method

- cmd/wallet-web/src/mixins/common/helper.js
Closes #1729 
Was able to reproduce locally by:
- Removing all credential output descriptors but "`VerifiableCredential`" (which is the default if the output descriptor cannot be found) in `credential-output-descriptors.json`
- In `readManifests` in `options.js`, comment [this line](https://github.com/trustbloc/wallet/blob/4b2d9826aaf36a57c1174f025a499a2559bd8ec9/cmd/wallet-web/src/store/modules/options.js#L396) so the local output descriptor file gets used.
- Save a PR card and University credential to wallet
- Use MultipleQuery 1 to query for a PR card and University credential - the error is seen here
Fix: To use a Set to add only unique `output_descriptors` to `credentialManifest`
> fix: CHAPI Multiple Credential Share failure

- cmd/wallet-web/src/store/modules/user.js
Closes #1331 
Added check for null before adding to `localStorage`. Then when `localStorage.getItem` is called, it will return `null` (not string 'null') if the key does not exist in `localStorage`. 
> chore: added check for null before adding to localStorage

- cmd/wallet-web/src/App.vue
- cmd/wallet-web/src/router/index.js
- cmd/wallet-web/src/store/modules/user.js
Related to #1809 
Added the Spinner icon to indicate to user that the wallet is loading while finishing user authentication. 
This was added as a temporary fix; in the future, the loading state should be the skeleton loaders for the corresponding page. 
https://user-images.githubusercontent.com/44453261/180890467-3c834808-9927-44da-8038-708ed41b7a58.mov
> fix: Added spinner as loading state for user authentication 

- cmd/wallet-web/src/pages/CredentialDetailsPage.vue
- cmd/wallet-web/src/pages/CredentialsPage.vue
- cmd/wallet-web/src/pages/OIDCSharePage.vue
- cmd/wallet-web/src/pages/WACISharePage.vue
Closes #1824 
What's changed:
If the 'credential name' property in a vc is empty, use the title from the credential manifest (returned from resolveManifest) instead - this is in [CredentialDetailsPage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-936eaa2bc7316c5c0a24b5d06f8fc304526a63a985db8a470a46a7a8d11baa0dR197), [CredentialsPage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-31f5afb2683cbf248197fb5dcf47321325ee209c4ab8cb27f5762017253c1905R236), [OIDCSharePage](https://github.com/trustbloc/wallet/compare/main...HeidiHan0000:wallet:issue-1824?expand=1#diff-c2fd5c10cf3198ca1ce1bd4a62ba8e5442d9bb5470fd409d31b42bc02b231cdcR230), and …
> fix: use title from credentialmanifest

- cmd/wallet-web/src/mixins/common/helper.js
- cmd/wallet-web/src/pages/CHAPISharePage.vue
- cmd/wallet-web/src/pages/MultipleQueryPage.vue
- cmd/wallet-web/src/pages/OIDCSavePage.vue
- cmd/wallet-web/src/pages/StorePage.vue
- cmd/wallet-web/src/pages/WACIIssuePage.vue
Closes #1832 
Added check for empty optional fields in the manifest before it gets resolved by `resolveManifest`. These are fields that are required by the wallet to display the credential properly but are not required in the credential manifest as per the [specs](https://identity.foundation/wallet-rendering/v0.0.1/#entity-styles) (ex. credential name, background colour, etc...).  
> feat: added check for empty optional properties for resolveManifest

- cmd/wallet-web/package-lock.json
- cmd/wallet-web/src/config/credential-output-descriptors.json
- cmd/wallet-web/src/mixins/common/helper.js
- cmd/wallet-web/src/pages/CHAPISharePage.vue
- cmd/wallet-web/src/pages/MultipleQueryPage.vue
- cmd/wallet-web/src/pages/OIDCSavePage.vue
- cmd/wallet-web/src/pages/StorePage.vue
- cmd/wallet-web/src/pages/WACIIssuePage.vue
- cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json
- test/fixtures/wallet-web/static/config/credential-output-descriptors.json
Closes https://github.com/trustbloc/sandbox/issues/1500 
Changes:
- added description property to the default `VerifiableCredential` in credential-output-descriptors.json
- use the default 'VerifiableCredential' output descriptor if default output descriptor for a certain credential does not exist
> fix: sandbox issue with credential manifests

- cmd/wallet-web/src/mixins/common/helper.js
- test/ui-automation/test/specs/credential-interaction-flow.js
Closes #1854 
- Added test case for issuing a VC for which wallet does not have default output descriptors for in https://github.com/trustbloc/wallet/blob/main/cmd/wallet-web/src/config/credential-output-descriptors.json
- Changes to resolveManifest:
- For the above case, `display.properties` were loaded into the credential manifest from the `credentialSubject` field of the VC only for CHAPI store - added the same steps for loading `display.properties` to `resolveManifest` so that the Verified Information properties would be displayed also for the WACI and OIDC issuance flows
- If `display.properties` were loaded from `credentialSubject`, capitalize first letter of the label
. | Before | After
| --- | --- | ---
WACI | <img width="400" alt="Screen Shot 2022-08-23 at 8 51 14 AM" …
> test: added test case for missing default manifest in wallet + resolveManifest changes

- cmd/wallet-web/package-lock.json
- cmd/wallet-web/package.json
- cmd/wallet-web/src/assets/img/qr-code-scan-icon.svg
- cmd/wallet-web/src/pages/InitiateProtocolPage.vue
- cmd/wallet-web/src/router/routes.js
https://user-images.githubusercontent.com/7862595/191410695-d1f3291e-6ada-4caf-9ed0-2fdd778a86c3.mov
closes #1879 
closes #1875 
Signed-off-by: Talwinder Kaur <talwinder.kaur@avast.com>
> feat: Add new demo page to handle issuance initiate request and qrcode scanner
