trustbloc/wallet

.codecov.yaml
Makefile
ci/azure-pipelines.yml
cmd/http-server/main_test.go
cmd/http-server/startcmd/start.go
cmd/issuer-agent-wasm/main.go
go.mod
pkg/didexchange/invitation/invitation.go
pkg/didexchange/invitation/invitation_test.go
scripts/check_unit_wasm.sh

feat: Create unit test for js invitation

---

Makefile
ci/azure-pipelines.yml
ci/version_var.sh
images/issuer-agent-wasm/Dockerfile
pkg/didexchange/invitation/invitation.go
pkg/didexchange/invitation/invitation_test.go
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

chore: Create issuer-wasm docker image

---

cmd/issuer-agent/web/package-lock.json
cmd/issuer-agent/web/package.json
cmd/rp-agent/web/package-lock.json
cmd/rp-agent/web/package.json
cmd/user-agent/web/package-lock.json
cmd/user-agent/web/package.json

chore: Update trustbloc/invitation version

---

.gitignore
Makefile
cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
scripts/generate_test_keys.sh
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: Add tls certs to http server

---

scripts/generate_test_keys.sh

chore: Fix tls cert

---

cmd/user-agent/web/src/views/StoreVC.vue
pkg/store/vc/store.go
pkg/store/vc/store_test.go

feat: User Agent - add VC friendly name to VC store

---

cmd/rp-agent/web/package-lock.json
cmd/rp-agent/web/package.json
cmd/rp-agent/web/src/App.vue
cmd/rp-agent/web/src/main.js
cmd/rp-agent/web/src/router/index.js
cmd/rp-agent/web/src/views/CreateInvitation.vue
cmd/rp-agent/web/src/views/GetVC.vue
cmd/rp-agent/web/src/views/Homepage.vue

feat: RP Agent - retrieve vc data from wallet (using CHAPI)

---

README.md
ci/version_var.sh
cmd/issuer-agent/wasm/go.mod
cmd/issuer-agent/wasm/go.sum
cmd/rp-agent/wasm/go.mod
cmd/rp-agent/wasm/go.sum
cmd/user-agent/wasm/go.mod
cmd/user-agent/wasm/go.sum
go.mod
go.sum

chore: Release 0.1.1

---

ci/version_var.sh
pkg/store/vc/store.go
pkg/store/vc/store_test.go

fix: Store vc directly in indexeddb

---

cmd/issuer-agent/wasm/go.mod
cmd/issuer-agent/wasm/go.sum
cmd/rp-agent/wasm/go.mod
cmd/rp-agent/wasm/go.sum
cmd/user-agent/wasm/go.mod
cmd/user-agent/wasm/go.sum
go.mod
go.sum

chore: Update aries-framework revision

---

cmd/issuer-agent/wasm/go.sum
cmd/rp-agent/wasm/go.sum
cmd/user-agent/wasm/go.sum
cmd/user-agent/web/src/App.vue
cmd/user-agent/web/src/router/index.js
cmd/user-agent/web/src/views/myVC.vue
go.mod
go.sum
pkg/store/vc/store.go

feat: Create QRCode for Verifiable Credential

---

ci/version_var.sh
docs/components/user_agent_wasm.md

chore: Release 0.1.2

---

ci/version_var.sh

chore: Complete Release 0.1.2

---

pkg/store/vc/store.go

feat: Replace QRCode from VC to Verifiable presentation

---

ci/azure-pipelines.yml

refactor: Fix Publish build failure - Removed RP/Issuer image generation/tagging

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json

feat: Update minimist dependency version to fix cve

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json

chore: Aries Framework Go dependency update

---

Makefile
cmd/trustbloc-agent-js-worker/go.sum
cmd/user-agent/src/main.js
go.mod
go.sum
scripts/build_trustbloc_agent_wasm.sh
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/config-data/stakeholder.one:8088.json
test/bdd/fixtures/agent-wasm/docker-compose.yml

chore: enable sidetree-mock tls

---

cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
cmd/user-agent/src/main.js
go.sum
scripts/check_lint.sh
test/bdd/fixtures/agent-wasm/docker-compose.yml

refactor: Externalize TrustBloc JS Startup opts

---

cmd/user-agent/src/components/index.js

feat: UI merge build failed fix

---

.gitattributes
cmd/user-agent/src/assets/scss/material-dashboard.scss

feat: Removing scss files from git local file storage.

---

ci/azure-pipelines.yml

fix: pull lfs images when publish images

---

cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/Interop.vue
cmd/user-agent/src/pages/StoreVC.vue
cmd/user-agent/src/router/index.js
cmd/user-agent/vue.config.js

- removed hardcoded content from store VC
- added "/interop" page which can be used perform store/get credentials
from CHAPI dynamically
- closes #101

feat: dynamic contents in store vc page

---

cmd/user-agent/package.json
cmd/user-agent/src/components/Tables/SimpleTable.vue
cmd/user-agent/src/pages/Dashboard.vue

Remove the hardcoded stored credentials and display the actual stored credentials 
closes #89
View Sample is below :

feat: Dynamic Verifiable Credential Dashboard

---

docs/test/test.md

docs: Changed user home page URL

---

cmd/user-agent/src/main.js
docs/test/test.md

fix: add default blocDomain

---

pkg/controller/command/didclient/command.go

fix: create did return wrong structure of DID

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/Interop.vue
cmd/user-agent/src/pages/Layout/ContentFooter.vue
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/config.json
test/bdd/fixtures/agent-wasm/docker-compose.yml
test/bdd/fixtures/agent-wasm/run-uni-resolver-web.sh

- added generate presentation with multiple VC support
- added DID auth (with interop)
- Look and Feel improvements with fixes
- Closes #109
- Closes #110

feat: CHAPI generate presentations & DID Auth

---

cmd/trustbloc-agent-js-worker/go.sum
cmd/user-agent/src/pages/DIDManagement.vue
go.mod
go.sum
test/bdd/fixtures/agent-wasm/.env

chore: update sideree-mock

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json

chore: update to latest aries

---

cmd/trustbloc-agent-js-worker/go.sum
go.mod
go.sum
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/config-data/stakeholder.one:8088.json

chore: update sidetree-mock

---

cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
pkg/controller/command/didclient/command.go
pkg/controller/command/didclient/command_test.go
pkg/controller/command/didclient/models.go

1. Enable P-256 did creation
2. Store private key in. Index DB. 
3. Make Create DID Json pretty. 
closes #113

feat: Support P-256 Create DID

---

cmd/trustbloc-agent-js-worker/go.sum
cmd/user-agent/src/pages/DIDManagement.vue
go.mod
go.sum
pkg/controller/command/didclient/command.go
pkg/controller/command/didclient/command_test.go
test/bdd/fixtures/agent-wasm/.env

chore: update trustbloc-did-method revision

---

cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/TablePresentation.vue
cmd/user-agent/src/router/index.js
test/bdd/fixtures/agent-wasm/docker-compose.yml

1. Fix Chapi header and footer 
2. Generate presentation with ED25519 and P-256 DID Key 
3.  Display both the source and QR Code of presentation while generating vp. 
closes #117

feat: Sign Presentation with P-256 DID and QR Fix

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/TablePresentation.vue
pkg/controller/command/didclient/command.go
pkg/controller/command/didclient/command_test.go
pkg/controller/command/didclient/models.go

chore: remove private key for p256

---

cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/Interop.vue
cmd/user-agent/src/pages/StoreVC.vue

- added store VP feature
- added get VP feature
- added get VC feature
- added web credential query support
- interop fixes
- Closes #124

feat: CHAPI - store VP, get VP, get VP, Web Cred Query

---

cmd/user-agent/package.json
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/TablePresentation.vue

feat: UI change to create other DID method

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/TablePresentation.vue
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: Support other DID methods

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/StoreVC.vue

- various CHAPI interop fixes
- Part of #128
TODO: signing with external DID and successfull verification test

feat: CHAPI inteop fixes

---

cmd/trustbloc-agent-js-worker/go.sum
go.mod
go.sum
test/bdd/fixtures/agent-wasm/.env

chore: update sidetree-mock image

---

cmd/trustbloc-agent-js-worker/go.sum
cmd/user-agent/package-lock.json
cmd/user-agent/package.json
go.mod
go.sum

chore: update aries revision

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/GetVC.vue

feat: CHAPI interop fixes

---

cmd/user-agent/src/pages/GetVC.vue

fix: minor credential query fix

---

cmd/user-agent/src/components/Tables/SimpleTable.vue
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/TablePresentation.vue
cmd/user-agent/src/router/index.js

Fixes below: 
1. VC Dashboard intermittent loading issue. 
2. Loader for create DID 
3. Saved DID dashboard
closes #88

feat: DID Dashboard and minor fixes

---

cmd/user-agent/src/pages/DIDManagement.vue

feat: DID Dashboard rendering bug

---

cmd/user-agent/src/pages/GetVC.vue

feat: CHAPI progress indicator

---

cmd/user-agent/src/components/Tables/SimpleTable.vue
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/Layout/ContentFooter.vue
cmd/user-agent/src/pages/TablePresentation.vue

1. Add spinner in generate presentation page 
2. Fix Create DID spinner show up on error issue 
3. Save and Display stored presentation on dashboard
4. Footer spell mistake
5. Fixed the layout of DID management
closes #136

feat: Dashboard update and UI fixes

---

cmd/user-agent/src/pages/Layout/MobileMenu.vue

feat: Dashboard button showing twice on mobile

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/Interop.vue

- Holder based dynamic VC table filtering
- Holder info will be available in generated presentations
- recent aries upgrade containing date parsing & issuer image fixes
- Closes #144

feat: latest interop fixes

---

cmd/trustbloc-agent-js-worker/go.sum
cmd/user-agent/package-lock.json
cmd/user-agent/package.json
go.mod
go.sum

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

chore: update aries-framework-go

---

cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/Layout/TopNavbar.vue

* `Cannot read property 'sidebarStore' of undefined`
* `Cannot read property 'length' of undefined`

refactor: Fixes errors in the browser console

---

cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Layout/ContentFooter.vue

fix: DID management UI fix

---

cmd/user-agent/scripts/setup_assets.sh

fix: remove gunzip for wasm

---

cmd/user-agent/scripts/setup_assets.sh

fix: add gzip and gunzip wasm

---

cmd/user-agent/src/pages/DIDManagement.vue

fix: select UI in safari

---

ci/version_var.sh
cmd/http-server/go.mod
cmd/http-server/go.sum
cmd/trustbloc-agent-js-worker/go.sum
cmd/user-agent/package-lock.json
cmd/user-agent/package.json
go.mod
go.sum

chore: edge-agent release v0.1.3

---

ci/version_var.sh

chore: complete release

---

cmd/user-agent/src/pages/Connections.vue
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/pages/TablePresentation.vue
cmd/user-agent/src/router/index.js

* adds the possibility to create an invitation
* adds the possibility to receive an invitation
* shows query connections
* fixes `vue.js` warnings
* fixes UI bug in `MyVC` page (when we click on `Generate Presentation ` several times, errors were duplicated)
Closes #153 

feat: Adds the possibility to create an invitation

---

cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/PageNotFound.vue
cmd/user-agent/src/pages/TablePresentation.vue
cmd/user-agent/src/router/index.js

- minor typo error 
- add dropdown icon in select  
closes #159

feat: Handle not found pages

---

.npmrc
cmd/user-agent/.npmrc
cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/scripts/setup_assets.sh
cmd/user-agent/src/main.js
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/GetVC.vue
cmd/user-agent/src/pages/TablePresentation.vue

feat: Import DID key to aries KMS

---

test/bdd/fixtures/agent-wasm/.env

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

ci: update sidetree-mock packages

---

cmd/user-agent/package.json
cmd/user-agent/src/pages/Connections.vue
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

* adds router service (docker)
* fixes minor UI bug

chore: Adds router service (docker)

---

cmd/user-agent/package-lock.json
cmd/user-agent/src/pages/IssueCredential.vue
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/router/index.js
docs/test/test.md
test/bdd/fixtures/agent-wasm/docker-compose.yml

Fully covered flow which starts from Offer.
How to test it?
First, you need to run the project. Follow [this](https://github.com/trustbloc/edge-agent/blob/master/docs/test/test.md#steps) instruction to do that.
1. Open the agents on the browser, [first agent](https://127.0.0.1:8091/dashboard) and [second agent](https://127.0.0.1:8071/dashboard) as well.
2. Go to `Connections` page and register the router for both agents. Use `http://localhost:10093/` as a router URL. Once the router was registered do not reload the page. It will lose the WebSocket connection.
3. On the connection page, you need to `Create Invitation`.  Copy the invitation to the buffer.
Make sure you copied only the invitation payload. e.g
```
{
"@id": "3f3fda9c-bfed-4b21-9d9f-cbc4d2209f84",
"@type": …
```

feat: Added Issue Credential protocol

---

cmd/user-agent/src/pages/DIDManagement.vue

fix: created DID saving incorrect metadata

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/Connections.vue
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/pages/PresentProof.vue
cmd/user-agent/src/router/index.js
docs/test/test.md
test/bdd/fixtures/agent-wasm/.env

This PR covers the flow which starts with sending a request presentation.
Want to test it? See [README](https://github.com/trustbloc/edge-agent/blob/master/docs/test/test.md).

Present proof ui

---

cmd/user-agent/package.json
cmd/user-agent/src/pages/Connections.vue
test/bdd/fixtures/agent-wasm/.env

feat: Shows threadID (Query connections)

---

cmd/user-agent/src/pages/WebWallet.vue
cmd/user-agent/src/pages/chapi/Get.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/get/getVP.js
cmd/user-agent/src/pages/chapi/wallet/index.js
scripts/check_license.sh

feat: Handle CHAPI request for presentation exchange

---

cmd/user-agent/package.json
test/bdd/fixtures/agent-wasm/.env

chore: Changes tag to a newer one

---

cmd/user-agent/src/pages/chapi/wallet/get/didConn.js

feat: webwallet did connection credential response as VP

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
test/user-agent/package-lock.json
test/user-agent/package.json

feat: didconnection credential type with proof

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/WebWallet.vue
cmd/user-agent/src/pages/chapi/wallet/common/presentationDef.js
cmd/user-agent/src/pages/chapi/wallet/index.js
test/user-agent/package-lock.json
test/user-agent/test/presentationDefQuery/presentationDef.spec.js
test/user-agent/test/presentationDefQuery/testdata.js

- added presentation definition query validation as per
RFC:
https://identity.foundation/presentation-exchange/#presentation-definition
- add tests for schema validation
- closes #198

feat: Presentation Definition Query Schema Validation

---

cmd/user-agent/src/pages/WebWallet.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

- get credential by query implemeneted in webwallet using presentation
exchange RFC
- Closes #202

feat: web wallet get credential by query

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

feat: webwallet  query - selective disclosure and no state handling

---

cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
test/user-agent/package-lock.json
test/user-agent/package.json

chore: upgrade aries version in tests

---

test/bdd/fixtures/agent-wasm/.env

fix: Update router port number

---

cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
test/bdd/fixtures/agent-wasm/docker-compose.yml

fix: Add issuance date to DIDConnection VC

---

Makefile
ci/azure-pipelines.yml
cmd/user-agent/src/pages/chapi/Get.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/register/register.js
scripts/check_js_intergation.sh
test/user-agent/karma.conf.js
test/user-agent/package-lock.json
test/user-agent/package.json
test/user-agent/scripts/setup_assets.sh
test/user-agent/test/common.js
test/user-agent/test/presentationDefQuery/presentationDef.spec.js
test/user-agent/test/wallet/testdata.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

- also added tests for presentation def query, requirement details

feat: end to end test for get crednetial by query

---

cmd/user-agent/package.json
cmd/user-agent/src/pages/Connections.vue
cmd/user-agent/src/pages/IssueCredential.vue
cmd/user-agent/src/pages/PresentProof.vue
cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
docs/test/test.md
test/bdd/fixtures/agent-wasm/.env
test/user-agent/package.json

This PR includes:
* a new format of notifications
* documentation for Issue Credential protocol

feat: Uses a new format of notifications

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
test/bdd/fixtures/agent-wasm/.env
test/user-agent/package-lock.json
test/user-agent/package.json

- reconnect mediator during CHAPI frame load (fix for problem of
websocket connection status going away issue)
- closes #217

feat: webwallet reconnect mediator during loading

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

feat: didexchange with RP to get RP DID Doc

---

cmd/trustbloc-agent-js-worker/go.sum
cmd/trustbloc-agent-js-worker/index.html
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
go.mod
go.sum
pkg/controller/command/didclient/command.go
pkg/controller/command/didclient/models.go
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/config-data/stakeholder.one_8088.json
test/bdd/fixtures/agent-wasm/config-data/testnet.trustbloc.local.json

Update did-method/sidetree
Closes #219
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>

chore: update did-method/sidetree

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

feat: webwallet -  concurrent consent credential request

---

cmd/http-server/startcmd/start.go
cmd/trustbloc-agent-js-worker/main.go
cmd/user-agent/src/main.js

feat: Use log level command line parameter for TrustBloc agent code

---

cmd/user-agent/src/pages/WebWallet.vue
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/pages/webWalletSamples.js

feat: webwallet concurrent request credential and test page improvements

---

cmd/user-agent/src/pages/webWalletSamples.js

fix: incorrect samples in webwallet demo page

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

fix: webwallet sendrequest attachment format

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

fix: DIDComm - Update consent credential request in Issue Credential

---

ci/azure-pipelines.yml
cmd/user-agent/src/pages/WebWallet.vue
cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/wallet/index.js
test/user-agent/karma.conf.js
test/user-agent/package-lock.json
test/user-agent/package.json
test/user-agent/test/common.js
test/user-agent/test/wallet/testdata.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

feat: webwallet DIDComm flow end to end tests

---

test/user-agent/karma.conf.js
test/user-agent/package-lock.json
test/user-agent/test/common.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

feat: webwallet end to end test - credential share over didcomm

---

cmd/user-agent/src/pages/chapi/wallet/common/presentationDefSchema.js
cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
test/user-agent/test/presentationDefQuery/presentationDef.spec.js
test/user-agent/test/presentationDefQuery/testdata.js
test/user-agent/test/wallet/testdata.js

feat: update to latest presentation exchange RFC

---

cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
test/user-agent/test/presentationDefQuery/presentationDef.spec.js
test/user-agent/test/presentationDefQuery/testdata.js

feat: presentation exchange - min-max-count for pick rule

---

cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/pages/webWalletSamples.js
test/user-agent/test/presentationDefQuery/presentationDef.spec.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

feat: remove presentation_location from presentation submission

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

refactor: Update AuthorizationCredential request

---

README.md
docs/components/web_wallet.md
docs/test/test.md

docs: web wallet docs

---

cmd/user-agent/src/main.js
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/pages/Relationships.vue
cmd/user-agent/src/router/index.js

feat: Added Relationships page

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/App.vue
cmd/user-agent/src/components/CreateInvitation/CreateInvitation.vue
cmd/user-agent/src/components/Mediator/Mediator.vue
cmd/user-agent/src/components/PublicInvitation/PublicInvitation.vue
cmd/user-agent/src/components/ReceiveInvitation/ReceiveInvitation.vue
cmd/user-agent/src/components/SidebarPlugin/SideBar.vue
cmd/user-agent/src/components/index.js
cmd/user-agent/src/events/index.js
cmd/user-agent/src/main.js
cmd/user-agent/src/pages/Connections.vue
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/pages/Relationships.vue
cmd/user-agent/src/store/index.js
cmd/user-agent/src/store/modules/connections.js
cmd/user-agent/src/store/modules/init.js
cmd/user-agent/src/store/modules/mediator.js
cmd/user-agent/src/store/modules/mode.js

This PR includes:
* Aries startup loader
* Added vuex support
* refactored `Connections` and `Relationships` 

refactor: Added vuex

---

cmd/user-agent/src/events/index.js
cmd/user-agent/src/pages/chapi/wallet/common/didExchange.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
cmd/user-agent/src/pages/webWalletSamples.js
cmd/user-agent/src/store/modules/mediator.js
test/user-agent/test/common.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

Uses out-of-band protocol instead of didexchange.

feat: Uses out-of-band protocol instead of didexchange

---

cmd/user-agent/src/components/Connections/Connections.vue
cmd/user-agent/src/components/CopyButton/CopyButton.vue
cmd/user-agent/src/components/CreateInvitation/CreateInvitation.vue
cmd/user-agent/src/components/Mediator/Mediator.vue
cmd/user-agent/src/components/PublicInvitation/PublicInvitation.vue
cmd/user-agent/src/components/ReceiveInvitation/ReceiveInvitation.vue
cmd/user-agent/src/components/index.js
cmd/user-agent/src/pages/Connections.vue
cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/pages/Relationships.vue
cmd/user-agent/vue.config.js

refactor: Reuses components (Connections and Relationships pages)

---

cmd/credential-mediator/configs/dev.js
images/credential-mediator/Dockerfile
scripts/generate_test_keys.sh
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: TLS for credential mediators

---

cmd/credential-mediator/components/Mediator.vue
images/credential-mediator/Dockerfile

feat: custom CHAPI wizard

---

cmd/credential-mediator/components/Mediator.vue
cmd/credential-mediator/configs/dev.js
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: CHAPI wizard custom empty state handling

---

cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js

fix: Presentations not being stored correctly in SDS

---

cmd/user-agent/src/main.js
cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/Store.vue
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
cmd/user-agent/src/pages/webWalletSamples.js
test/user-agent/test/common.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js
test/user-agent/test/wallet/walletStore.spec.js

feat: didconnect to store credentials along with manifest

---

cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/Get.vue
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js

- showing list of credentials being sent along with invitation
- closes #311

feat: CHAPI didconnect view updates

---

cmd/user-agent/src/pages/chapi/Store.vue
test/user-agent/test/wallet/walletStore.spec.js

feat: Pre-fill friendly name of the credential while storing credential

---

cmd/http-server/startcmd/start.go
cmd/user-agent/src/main.js
cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/Store.vue
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
pkg/controller/command/credentialclient/command_test.go
pkg/controller/command/didclient/command_test.go
pkg/controller/command/presentationclient/command_test.go
pkg/controller/command/sdscomm/messages.go
pkg/controller/command/sdscomm/sdscomm.go
pkg/controller/command/sdscomm/sdscomm_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go

feat: Make SDS server URL and agent label optional for TrustBloc agent

---

cmd/user-agent/src/components/AssociatedPresentation/AssociatedPresentation.vue
cmd/user-agent/src/components/index.js
cmd/user-agent/src/main.js
cmd/user-agent/src/pages/Relationships.vue
cmd/user-agent/src/store/index.js
cmd/user-agent/src/store/modules/presentation.js

feat: Adds associated presentation

---

cmd/user-agent/src/assets/img/govn.png
cmd/user-agent/src/pages/WebWallet.vue
cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/Governance.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/pages/webWalletSamples.js

feat: webwallet and governance framework integration

---

cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/Governance.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

chore: follow up for user trust consent

---

ci/version_var.sh

chore: complete release v0.1.4

---

cmd/user-agent/src/main.js
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/chapi/Login.vue
cmd/user-agent/src/pages/chapi/Logout.vue
cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
cmd/user-agent/src/router/index.js
cmd/user-agent/src/store/index.js
cmd/user-agent/src/store/modules/user.js

feat: access control for wallet dashboard & vuex based login

---

cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
cmd/trustbloc-agent-js-worker/main.go
cmd/user-agent/src/main.js
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
cmd/user-agent/src/pages/chapi/wallet/register/register.js
cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
pkg/controller/command/credentialclient/command.go
pkg/controller/command/credentialclient/command_test.go
pkg/controller/command/didclient/command.go
pkg/controller/command/didclient/command_test.go
pkg/controller/command/presentationclient/command.go
pkg/controller/command/presentationclient/command_test.go
pkg/controller/command/sdscomm/models.go
pkg/controller/command/sdscomm/sdscomm.go
pkg/controller/command/sdscomm/sdscomm_test.go
pkg/controller/controller.go
test/user-agent/test/common.js

feat: Use username from login for SDS vault creation

---

cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js

fix: add retry for router register

---

cmd/user-agent/src/main.js
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/TablePresentation.vue
cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/Login.vue
cmd/user-agent/src/pages/chapi/Logout.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/Store.vue
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/pages/chapi/wallet/register/register.js
cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
cmd/user-agent/src/store/modules/user.js
test/user-agent/package-lock.json
test/user-agent/package.json
test/user-agent/test/common.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js
test/user-agent/test/wallet/walletStore.spec.js

- wallet registration (DID creation, mediator registration) will happen 
only during very first login
- getting logged in user for all wallet operations
- wallet metadata including connections will not be cleared during logout
- user state based refactoring
- closes #339

feat: user vuex state for webwallet

---

cmd/trustbloc-agent-js-worker/go.sum
go.mod
go.sum
test/bdd/fixtures/agent-wasm/.env

Update sidetree, did-method
Closes #340
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>

chore: update sidetree, did-method

---

cmd/user-agent/src/main.js
cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/chapi/DIDAuth.vue
cmd/user-agent/src/pages/chapi/DIDConnect.vue
cmd/user-agent/src/pages/chapi/GetCredentials.vue
cmd/user-agent/src/pages/chapi/Login.vue
cmd/user-agent/src/pages/chapi/Logout.vue
cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/Store.vue
cmd/user-agent/src/store/modules/user.js
test/user-agent/test/common.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js
test/user-agent/test/wallet/walletStore.spec.js

- namespaced aries based on userid, to avoid collission of agent data
- closes #346

feat: webwallet - aries per user login

---

cmd/user-agent/src/pages/Layout/DashboardLayout.vue
cmd/user-agent/src/pages/Layout/TopNavbar.vue
cmd/user-agent/src/pages/TablePresentation.vue
cmd/user-agent/src/pages/chapi/Login.vue
cmd/user-agent/src/router/index.js

- show only wallet related pages in default mode
- closes #348

chore: refactor user agent wallet left navigation

---

test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

chore: update to latest trustbloc-did-method

---

cmd/user-agent/src/assets/img/sidebar-2.jpg
cmd/user-agent/src/assets/img/topbar-2.jpg
cmd/user-agent/src/assets/scss/md/_sidebar-and-main-panel.scss
cmd/user-agent/src/components/SidebarPlugin/SideBar.vue
cmd/user-agent/src/components/Tables/SimpleTable.vue
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/pages/Layout/TopNavbar.vue
cmd/user-agent/src/router/index.js
cmd/user-agent/src/store/modules/user.js

- warning for lost mediator connection
- updated dashboard credential list
- logout options available for all the pages
- Closes #364

feat: updated UI for wallet dashboard

---

cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
cmd/user-agent/src/pages/Dashboard.vue
cmd/user-agent/src/store/modules/options.js

- blinded routing configuration
- some minor UI fixes
- closes #366

feat: blinded routing configuration

---

cmd/user-agent/.npmrc
test/user-agent/.npmrc

fix: #369 missing npm registry config

---

cmd/http-server/go.mod
cmd/http-server/go.sum
go.mod
go.sum
pkg/restapi/common/common.go
pkg/restapi/common/common_test.go
pkg/restapi/common/httphandler.go
pkg/restapi/common/httphandler_test.go
pkg/restapi/oidc/dependencies.go
pkg/restapi/oidc/helper.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
pkg/restapi/oidc/transientData.go

~~depends on #359~~ 
closes #357 

feat: #357 http-server OIDC /login endpoint

---

cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
cmd/user-agent/src/store/modules/mediator.js
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: Router - replace aries-agent with hub-router

---

pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
pkg/restapi/oidc/persistedData.go

~~depends on #387~~ 
fixes #381 

fix: #381 overwriting existing user records on every login

---

cmd/http-server/startcmd/start.go
cmd/user-agent/src/main.js
cmd/user-agent/src/pages/chapi/BlockNoAuth.vue
cmd/user-agent/src/pages/chapi/Worker.vue
cmd/user-agent/src/pages/chapi/wallet/register/register.js
cmd/user-agent/vue.config.js

- changed vue config public path from '/wallet' to '/wallet/' to follow
vue public path convention. (This was causing `//` in wallet worker URLs
causing 404 errors in vue-cli-service serve)
- fixed intermittent CORS issue in wallet iframes
- closes #398

fix: cors and vue-cli-service serve issue fixes

---

cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/pages/chapi/wallet/index.js
cmd/user-agent/src/pages/chapi/wallet/register/register.js
cmd/user-agent/src/store/modules/user.js

- added messenger service in webwallet
- added share router peer DID steps during didconnect step with RP &
Issuer.
- closes #407
- closes #408

feat: webwallet blinded routing during didconnect - setup

---

test/bdd/fixtures/agent-wasm/.env

Pull changes related to Blinded Routing https://github.com/trustbloc/hub-router/issues/23

chore: Hub-Router image version update

---

cmd/agent-js-worker/go.mod
cmd/agent-js-worker/go.sum
cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
cmd/user-agent/src/store/modules/user.js
docs/test/test.md
test/bdd/fixtures/agent-wasm/.env

feat: webwallet blinded routing -  requesting peer DID from router

---

Makefile
cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/store/modules/user.js

feat: webwallet blinded routing - request peer DID from other party

---

cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js

feat: webwallet messaging correlate message replies

---

test/user-agent/test/wallet/walletCredentialQuery.spec.js

test: fix race conditions in bdd tests

---

cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
cmd/user-agent/src/store/modules/user.js
test/user-agent/test/common.js
test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

feat: webwallet js bddtests - blinded didconnect from issuer

---

cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
cmd/user-agent/src/store/modules/user.js
test/bdd/fixtures/agent-wasm/.env
test/user-agent/test/common.js
test/user-agent/test/mocks/adapters/issuerAdapter.js

chore: update to latest hub-router and message updates

---

ci/azure-pipelines.yml
docs/test/test.md

ci: Fixes ci (Publish job)

---

cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js

fix:  retry for router register

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json

chore: fix security vulnerabilities

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
test/user-agent/test/common.js
test/user-agent/test/mocks/adapters/issuerAdapter.js

chore: RP blinded routing enabled only for bddtests

---

cmd/user-agent/src/store/modules/user.js
test/user-agent/test/common.js
test/user-agent/test/mocks/adapters/issuerAdapter.js

fix: incorrect message types in blinded routing

---

cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js

feat: blinded routing - retries on failed 'diddoc-req'

---

cmd/user-agent/src/pages/chapi/wallet/common/messaging.js

feat: webwallet - retry msg send/reply on failed response

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
test/user-agent/package-lock.json
test/user-agent/package.json

chore: update to latest agent-sdk

---

cmd/user-agent/src/pages/DIDManagement.vue
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/pages/chapi/wallet/register/register.js

feat: webwallet - do not share DID from RP connection to issuer

---

cmd/user-agent/src/pages/chapi/wallet/get/didAuth.js

- fix for issue where wallet DID showing up in from demo1 CHAPI pages
- closes #449

fix: wallet's default DID showing up in demo1 DID list

---

cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
scripts/check_js_integration.sh
test/user-agent/package-lock.json

fix: Fixes createTrustBlocDID function

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
test/bdd/fixtures/agent-wasm/.env
test/user-agent/package-lock.json
test/user-agent/package.json

chore: Updates agent-sdk version

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/store/modules/user.js
test/user-agent/karma.conf.js
test/user-agent/test/common.js
test/user-agent/test/mocks/adapters/issuerAdapter.js
test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
test/user-agent/test/wallet/walletCredentialQuery.spec.js

- added bddtests
- currently marked as 'betaFeature', enabled only in tests
- Closes #454

feat: webwallet DID Comm flow - request for new RP DID

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

fix: webwallet didcomm - incorrect wallet DID being sent to RP

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

feat: webwallet DIDComm - enable did doc req feature for RP

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/user-agent/src/store/modules/user.js

fix: incorrect message type and retry on did doc request

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js

- fixing issue where some of the message from RP comes in byte format
- Part of #434

fix: webwallet to RP integration issue fix

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json

chore: update edge-sdk revision

---

cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
test/user-agent/test/common.js

chore: enable RP blinded routing

---

Makefile
README.md
docs/components/web_wallet.md
docs/dev/dev-mode.md
scripts/user_agent_dev_start.sh

docs: webwallet docs for all supported features

---

README.md

fix: Broken dev mode link

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
test/bdd/fixtures/agent-wasm/.env
test/user-agent/package-lock.json
test/user-agent/package.json

Update agent-sdk, sidetree, did-method
Closes #463
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>

chore: update agent-sdk

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json

chore: update agent-sdk revision

---

test/bdd/fixtures/agent-wasm/.env

chore: hub-router dependency update

---

cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
test/bdd/bdd_test.go
test/bdd/features/healthcheck.feature
test/bdd/go.mod
test/bdd/go.sum
test/bdd/pkg/healthcheck/steps.go
test/user-agent/package-lock.json

feat: http-server healthcheck endpoint

---

cmd/user-agent/package.json
test/bdd/fixtures/agent-wasm/.env

chore: update aries-framework-go and did-method revision

---

cmd/http-server/startcmd/start.go
cmd/user-agent/src/store/modules/options.js
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

Hardcoded to IndexedDB for now. In the future this will be customizable.

fix: agent-sdk missing storage type

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
test/bdd/fixtures/agent-wasm/.env
test/user-agent/package-lock.json
test/user-agent/package.json
test/user-agent/test/common.js

chore: update sidetree-mock and did-method

---

test/bdd/fixtures/agent-wasm/.env

chore: Hub-router docker update

---

cmd/http-server/go.mod
cmd/http-server/go.sum
cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
pkg/restapi/device/operations.go
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: Hook Device REST handlers into http-server

---

cmd/http-server/go.sum
cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
go.sum
pkg/restapi/oidc/models.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
test/bdd/fixtures/agent-wasm/.env
test/bdd/fixtures/agent-wasm/docker-compose.yml

- Create user secret
- Split the user secret
- Integrate AuthZ key server to create the keystore
part of #485 

feat: AuthZ Hub-KMS basic integration

---

test/bdd/fixtures/agent-wasm/.env

chore: update edv docker image version

---

cmd/http-server/startcmd/start.go
cmd/user-agent/src/pages/Layout/TopNavbar.vue
cmd/user-agent/src/pages/chapi/RegisterDevice.vue
cmd/user-agent/src/pages/chapi/wallet/device/register.js
cmd/user-agent/src/pages/chapi/wallet/index.js
pkg/restapi/device/operations.go
pkg/restapi/device/operations_test.go
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: Device Registration vue change

---

cmd/http-server/startcmd/start.go
cmd/http-server/startcmd/start_test.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
test/bdd/fixtures/agent-wasm/docker-compose.yml

feat: Create User SDS Vault during onboarding

---

images/user-agent/templates/default.conf.template
test/bdd/fixtures/user-agent/.env
test/bdd/fixtures/user-agent/docker-compose.yml

fix: Update ops-kms store type and edv port variable

---

pkg/restapi/oidc/models.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
test/user-agent/package-lock.json

chore: unblock #506 by temporarily storing bootstrap data locally

---

cmd/user-agent/package-lock.json
cmd/user-agent/package.json
cmd/user-agent/src/store/modules/options.js
images/user-agent/Dockerfile
test/bdd/fixtures/user-agent/docker-compose.yml
test/user-agent/package-lock.json
test/user-agent/package.json

feat: EDV storage

---

ci/azure-pipelines.yml
docs/test/test.md
test/bdd/bdd_test.go
test/bdd/fixtures/user-agent/.env
test/bdd/fixtures/user-agent/docker-compose.yml
test/bdd/fixtures/user-agent/hydra-config/bdd_auth-rest-hydra_configure.sh
test/bdd/fixtures/user-agent/hydra-config/bdd_hydra_configure.sh
test/bdd/fixtures/user-agent/hydra-config/demo_auth-rest-hydra_configure.sh
test/bdd/fixtures/user-agent/mysql-config/mysql_config.sql
test/bdd/fixtures/user-agent/oidc-config/bdd_providers.yaml
test/bdd/fixtures/user-agent/oidc-config/demo_providers.yaml
test/bdd/pkg/login/steps.go

test: Integrate with hub-auth

---

cmd/wallet-server/startcmd/start.go
cmd/wallet-server/startcmd/start_test.go
pkg/restapi/oidc/models.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
test/bdd/fixtures/wallet-web/docker-compose.yml

feat: Update half secret in hub-auth

---

Makefile
docs/test/test.md
pkg/restapi/oidc/models.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose.yml

chore: update hub-kms revision

---

docs/components/web_wallet.md
docs/test/test.md
pkg/restapi/common/store/cookie/store.go
scripts/generate_test_keys.sh
test/bdd/fixtures/wallet-web/docker-compose.yml
test/bdd/fixtures/wallet-web/hydra-config/demo_auth-rest-hydra_configure.sh

This PR fixes:
* cookie usage in iframe
* cors subdomain issue

fix: Fixes cookie usage in iframe

---

pkg/restapi/common/store/cookie/store.go

fix: Fixes cookie path

---

cmd/wallet-web/src/store/modules/options.js
cmd/wallet-web/src/store/modules/user.js

fix: Remove EDV Vault ID storage workaround

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
cmd/wallet-web/src/pages/chapi/wallet/didcomm/mediator.js
cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/wallet-web/src/pages/chapi/wallet/index.js
cmd/wallet-web/src/pages/chapi/wallet/register/register.js
cmd/wallet-web/src/store/modules/user.js
test/wallet-web/package-lock.json
test/wallet-web/package.json
test/wallet-web/test/common.js
test/wallet-web/test/mocks/adapters/issuerAdapter.js
test/wallet-web/test/wallet/walletCredentialQuery.blinded.spec.js
test/wallet-web/test/wallet/walletCredentialQuery.spec.js

- using mediator, blinded routing & message services from agent-sdk

feat: migration to agent-sdk commands

---

cmd/wallet-server/startcmd/start.go
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/wallet/device/login.js
cmd/wallet-web/src/pages/chapi/wallet/index.js
pkg/restapi/device/operations.go
pkg/restapi/device/operations_test.go

feat: Login device with touch ID implementation

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/wallet-web/package-lock.json
test/wallet-web/package.json

chore: Update agent-sdk version

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/store/modules/options.js
pkg/restapi/common/store/user/store.go
pkg/restapi/oidc/models.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
pkg/restapi/oidc/signer.go
test/bdd/fixtures/wallet-web/docker-compose.yml
test/wallet-web/package-lock.json
test/wallet-web/package.json

feat: Pass half secret share to hub-kms

---

ci/azure-pipelines.yml
docs/test/test.md
go.mod
go.sum
pkg/restapi/oidc/operations.go
scripts/generate_test_keys.sh
test/bdd/fixtures/bdd-edv-oathkeeper/config.yaml
test/bdd/fixtures/bdd-edv-oathkeeper/rules/resource-server.json
test/bdd/fixtures/edv-oathkeeper/config.yaml
test/bdd/fixtures/edv-oathkeeper/rules/resource-server.json
test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose.yml

feat: Add oathkeeper for edv

---

pkg/restapi/oidc/models.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go
test/bdd/pkg/login/steps.go

closes #540 
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

feat: Wallet onboard - create edvOps and edvHMAC keys

---

cmd/wallet-web/src/pages/chapi/RegisterDevice.vue
cmd/wallet-web/src/pages/chapi/wallet/device/register.js

closes #552
Signed-off-by: serenahacker <serenahacker@gmail.com>

fix: Remove alert message while registering device

---

test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose.yml

chore: enable hub-kms to hub-auth integration

---

cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/wallet-web/src/pages/chapi/wallet/register/walletManager.js

feat: Connections will not be store in local storage

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/bdd/fixtures/wallet-web/.env
test/wallet-web/package-lock.json
test/wallet-web/package.json

chore: Update agent-sdk and hub-kms dependency

---

test/bdd/go.sum

due to previous pr didn't have bdd test go.sum file, this pr updates this file
Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

chore: update bdd test go.sum with latest aries-framework-go

---

docs/test/test.md

docs: Add ops kms url to localhosts

---

cmd/wallet-web/src/components/SidebarPlugin/index.js
cmd/wallet-web/src/pages/Dashboard.vue

fix: Addressing console warnings.

---

test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose.yml

feat: Update EDV server version (which now supports batch requests)

---

test/bdd/fixtures/wallet-web/docker-compose.yml

fix: add EDV_BATCH_LIMIT to bdd test

---

test/bdd/fixtures/wallet-web/docker-compose.yml

chore: disable edv caching and batching

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
cmd/wallet-web/src/pages/chapi/wallet/didmgmt/didManager.js
cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
cmd/wallet-web/src/pages/chapi/wallet/register/register.js
cmd/wallet-web/src/pages/chapi/wallet/register/walletManager.js
cmd/wallet-web/src/store/modules/user.js
test/wallet-web/package-lock.json
test/wallet-web/package.json

feat: Removes indexdb usage

---

cmd/wallet-web/src/pages/chapi/wallet/get/didAuth.js

fix: DIDAuth store error

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/bdd/fixtures/wallet-web/.env
test/wallet-web/package-lock.json
test/wallet-web/package.json

Update did-method, sidetree-mock, agent-sdk
Closes #585
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>

chore: update did-method, sidetree-mock, agent-sdk

---

test/bdd/fixtures/wallet-web/.env

Updated EDV server is faster now.

feat: Update EDV server version

---

cmd/wallet-web/src/pages/DIDManagement.vue

fix: Stores DID id (metadata)

---

pkg/restapi/oidc/operations_test.go
pkg/restapi/oidc/webkms_test.go

Fixes some of the missing test coverage from PR #578 

chore: bump test coverage

---

cmd/wallet-web/src/pages/DIDManagement.vue
cmd/wallet-web/src/pages/Layout/DashboardLayout.vue

Signed-off-by: serena.hacker <Serena.Hacker@securekey.com>

fix: replace DID with Digital Identity

---

cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
cmd/wallet-web/src/pages/chapi/wallet/register/register.js

fix: Skip user registration for onboarded user

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/wallet-web/package-lock.json
test/wallet-web/package.json

Latest agent-sdk brings improved EDV REST performance

feat: Update agent-sdk version

---

test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose.yml

chore: upgrade to the latest hub-kms

---

cmd/wallet-server/go.sum
cmd/wallet-web/package.json
cmd/wallet-web/src/assets/img/sidebar-2.jpg
cmd/wallet-web/src/assets/img/topbar-2.jpg
cmd/wallet-web/src/assets/img/wallet.jpg
cmd/wallet-web/src/main.js
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/RegisterDevice.vue
cmd/wallet-web/src/pages/chapi/wallet/device/login.js
test/bdd/fixtures/wallet-web/.env
test/bdd/go.sum
test/bdd/mock/demo-login-consent-server/templates/consent.html

1. Redesign Login Page
2. Show Login/Register button for non-registered user. 
3. Pop up Login with Touch ID option for the registered user. 
4. Show the register Device button only for the non-registered device. 
5. Image resolution is reduced 

fix: Login UX change and alert fixes.

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/wallet/register/register.js
test/bdd/fixtures/wallet-web/.env
test/wallet-web/package-lock.json
test/wallet-web/package.json

chore: update dependencies

---

ci/version_var.sh

chore: Complete Release 0.1.5

---

cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/store/modules/options.js

fix: Chapi UI Button alignment

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

- fixed `hightlight.js` Dependabot security warning

fix: security vulnerability

---

cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
cmd/wallet-web/src/pages/chapi/wallet/register/register.js

chore: Log wallet connect execute time

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/DIDManagement.vue
cmd/wallet-web/src/pages/chapi/Login.vue

Signed-off-by: serena.hacker <Serena.Hacker@securekey.com>

fix: DID table updates automatically and loading screen

---

cmd/wallet-web/src/pages/chapi/wallet/register/register.js

- remove create-invitation in advance
- part of #614

feat: mediator connect performance enhancement

---

cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/wallet/register/register.js

- mediator connector will run in parallel to did creation
- first time post login register process will not be blocked by did
creattion, save, mediator connect
- closes #617

feat: wallet register to run in background after login

---

cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/wallet/register/register.js
cmd/wallet-web/src/store/modules/user.js

- dashboard will show status of background user registration process and
will report error if in case of failure
- closes #621

feat: vuex state to track background user registration

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
test/wallet-web/package-lock.json
test/wallet-web/package.json

feat: wallet blinded routing to use agent-sdk commands

---

cmd/wallet-web/src/assets/scss/card-content.scss
cmd/wallet-web/src/components/CredentialCards/CrudeProductCard.vue
cmd/wallet-web/src/components/CredentialCards/DriversLicense.vue
cmd/wallet-web/src/components/CredentialCards/GeneralCard.vue
cmd/wallet-web/src/components/CredentialCards/JsonModal.vue
cmd/wallet-web/src/components/CredentialCards/MillTestCard.vue
cmd/wallet-web/src/components/CredentialCards/PermanentResidentCard.vue
cmd/wallet-web/src/components/CredentialCards/StudentCard.vue
cmd/wallet-web/src/components/CredentialCards/TravelCard.vue
cmd/wallet-web/src/components/CredentialCards/UniversityCard.vue
cmd/wallet-web/src/pages/Dashboard.vue

feat: Create card like view for stored credentials

---

test/bdd/fixtures/wallet-web/.env
test/wallet-web/package-lock.json

chore: update edv and kms image urls to new location

---

Makefile
ci/azure-pipelines.yml
ci/version_var.sh
images/wallet-server/Dockerfile
images/wallet-web/Dockerfile
test/bdd/fixtures/wallet-web/.env

Signed-off-by: Troy Ronda <troy.ronda@securekey.com>

ci: migrate to ghcr

---

test/bdd/fixtures/wallet-web/.env

chore: upgrade to the latest kms image

---

Makefile
scripts/check_js_integration.sh
scripts/run-openapi-demo.sh
scripts/wallet_web_dev_start.sh
scripts/wallet_web_start.sh
test/bdd/bdd_test.go
test/bdd/fixtures/.gitignore
test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose-server.yml
test/bdd/fixtures/wallet-web/docker-compose-web.yml

chore: remove dependency of web components in open api demo

---

cmd/wallet-server/startcmd/start.go
test/bdd/mock/bddtest-login-consent-server/main.go
test/bdd/pkg/bddcontext/context.go

chore: Changes TLS version

---

Makefile
cmd/wallet-server/startcmd/start.go
cmd/wallet-server/startcmd/start_test.go
pkg/restapi/common/common.go
pkg/restapi/common/logutil/util.go
pkg/restapi/internal/mocks/protocol/outofband.go
pkg/restapi/internal/mocks/protocol/provider.go
pkg/restapi/wallet/chapibridge/models.go
pkg/restapi/wallet/chapibridge/operations.go
pkg/restapi/wallet/chapibridge/operations_test.go
pkg/restapi/wallet/controller.go
pkg/restapi/wallet/controller_test.go
scripts/generate-openapi-demo-specs.sh
test/bdd/fixtures/wallet-web/docker-compose-openapi.yml
test/bdd/fixtures/wallet-web/docker-compose-server.yml

feat: wallet server - create app invitation URL

---

cmd/wallet-web/src/pages/chapi/wallet/register/register.js

fix: flush user registration settings

---

Makefile

chore: disable validate open api spec

---

Makefile
cmd/wallet-server/startcmd/agentconfig.go
cmd/wallet-server/startcmd/start.go
cmd/wallet-server/startcmd/start_test.go
go.mod
go.sum
pkg/restapi/internal/mocks/mock_webhook.go
pkg/restapi/wallet/chapibridge/models.go
pkg/restapi/wallet/chapibridge/operations.go
pkg/restapi/wallet/chapibridge/operations_test.go
pkg/restapi/wallet/chapibridge/store.go
pkg/restapi/wallet/chapibridge/store_test.go
pkg/restapi/wallet/controller.go
pkg/restapi/wallet/controller_test.go

feat: wallet-server didexchange and wallet app profile management

---

pkg/restapi/wallet/chapibridge/models.go
pkg/restapi/wallet/chapibridge/operations.go
pkg/restapi/wallet/chapibridge/operations_test.go
pkg/restapi/wallet/controller.go
pkg/restapi/wallet/controller_test.go

feat: wallet-server send chapi request

---

pkg/restapi/wallet/chapibridge/models.go
pkg/restapi/wallet/chapibridge/operations.go
pkg/restapi/wallet/chapibridge/operations_test.go

feat: wallet server - request app profile - wait for connection completed option

---

cmd/wallet-server/startcmd/start.go
go.mod
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go

This PR adds caching for jsonld document loader to speed up ZCAP.

perf: zcapld caching logic

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/wallet-web/package-lock.json
test/wallet-web/package.json

chore: upgrade to the latest agent-sdk

---

cmd/wallet-web/src/pages/DIDManagement.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/chapi/DIDAuth.vue
cmd/wallet-web/src/pages/chapi/GetCredentials.vue
cmd/wallet-web/src/store/modules/options.js
test/bdd/fixtures/wallet-web/config.json
test/bdd/fixtures/wallet-web/docker-compose-web.yml

- updating UI HTML/Vue elements to support webdriver selenium selectors
- closes #668

feat: wallet web UI -  webdriver support

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/WebWallet.vue
cmd/wallet-web/src/pages/chapi/Get.vue
cmd/wallet-web/src/pages/chapi/QueryByFrame.vue
cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
cmd/wallet-web/src/pages/chapi/wallet/index.js
cmd/wallet-web/src/pages/webWalletSamples.js
cmd/wallet-web/src/store/modules/options.js
test/bdd/fixtures/wallet-web/.env
test/bdd/mock/demo-login-consent-server/go.sum

- Query by frame support
- closes #674

feat: selective disclosure in webwallet

---

test/bdd/fixtures/wallet-web/.env

chore: Update EDV Docker image

---

cmd/wallet-server/go.mod
cmd/wallet-server/go.sum

chore: Update aries-framework-go-ext commit versions

---

ci/version_var.sh

chore: complete release v0.1.6

---

cmd/wallet-web/src/pages/WebWallet.vue
cmd/wallet-web/src/pages/chapi/Get.vue
cmd/wallet-web/src/pages/chapi/MultipleQuery.vue
cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js
cmd/wallet-web/src/pages/chapi/wallet/index.js
cmd/wallet-web/src/pages/webWalletSamples.js

- supports `QueryByExample` & `QueryByFrame`
- closes #683

feat: multiple query support for webwallet GET

---

cmd/wallet-server/startcmd/start.go
cmd/wallet-server/startcmd/start_test.go
pkg/restapi/common/store/cookie/store.go
pkg/restapi/device/operations.go
pkg/restapi/device/operations_test.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go

chore: make session cookie max age configurable

---

cmd/wallet-web/src/pages/chapi/wallet/common/presentationDefSchema.js
cmd/wallet-web/src/pages/chapi/wallet/common/presentationExchange.js
test/wallet-web/test/presentationDefQuery/presentationDef.spec.js
test/wallet-web/test/presentationDefQuery/testdata.js
test/wallet-web/test/wallet/testdata.js
test/wallet-web/test/wallet/walletCredentialQuery.spec.js

refactor: update presentation-exchange impl

---

cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js

fix: QueryByFrame to support undefined 'example'

---

cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js

fix: use DID from credential subject ID to present

---

cmd/wallet-web/src/components/CredentialCards/JsonModal.vue

fix: Fix the scrollbar issue on wallet cred dialog box.

---

pkg/restapi/device/appleattestation.go
pkg/restapi/device/operations.go
pkg/restapi/device/operations_test.go

feat: add support for pk creds generated by apple touch/face id

---

test/bdd/fixtures/wallet-web/.env

chore: update hub-auth docker image

---

images/wallet-web/templates/default.conf.template

chore: wallet-web - add healthcheck endpoint

---

test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/oidc-config/bdd_providers.yaml
test/bdd/fixtures/wallet-web/oidc-config/demo_providers.yaml

chore: update hub-auth image and config file

---

cmd/wallet-web/src/pages/chapi/PresentationDefQuery.vue

chore: added id tag in didcomm vcs presentation screen

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/wallet-web/package-lock.json
test/wallet-web/package.json

chore: update agent-sdk-web

---

cmd/wallet-web/src/main.js

UI changes are in transition, we will get rid of this theme once
dashboard UI changes are merged in the following PRs.

fix: Temporary fix to not break the automation test

---

cmd/wallet-web/package-lock.json

fix: update package-lock.json

---

cmd/wallet-web/src/main.js
cmd/wallet-web/src/pages/Layout/ContentFooter.vue
cmd/wallet-web/src/pages/chapi/Login.vue

fix: Update login page font and color scheme

---

cmd/wallet-web/src/assets/img/wallet.png
cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
cmd/wallet-web/src/pages/Layout/Content.vue
cmd/wallet-web/src/pages/Layout/ContentFooter.vue
cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
cmd/wallet-web/src/pages/Layout/TopNavbar.vue
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/Settings.vue

feat: Implement sidebar and dashboard upgrade to new UI

---

cmd/wallet-web/src/pages/chapi/Login.vue

fix: Fix login issue in sandbox

---

cmd/wallet-web/src/pages/chapi/Login.vue

fix: Fix login get started button for edge-sandbox

---

cmd/wallet-web/src/pages/chapi/Login.vue

fix: Enable the beat loader in edge-agent login

---

cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
cmd/wallet-web/src/pages/chapi/Login.vue

fix: Add temporarily Did management sidelink to fix integration

---

cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
cmd/wallet-web/src/pages/DIDManagement.vue
cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
cmd/wallet-web/src/pages/Layout/TopNavbar.vue

fix: Update did management unclickable buttons

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/wallet-web/package-lock.json
test/wallet-web/package.json

chore: update to agent-sdk with enabled remote context fetching

---

cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
cmd/wallet-web/src/pages/WebWallet.vue

feat: Update stored credential layout in the dashboard

---

cmd/wallet-web/src/assets/scss/md/_inputs.scss
cmd/wallet-web/src/assets/scss/md/_sidebar-and-main-panel.scss
cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
cmd/wallet-web/src/pages/chapi/Logout.vue

Fixes #754
Signed-off-by: Anton Biriukov anton.biriukov@securekey.com

fix: added logout button, fixed sidebar width

---

cmd/wallet-web/package-lock.json

chore: Update package lock json file

---

package-lock.json
test/wallet-web/package-lock.json

chore: Specify lockfile version

---

cmd/wallet-web/src/pages/chapi/Signup.vue
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/options.js
images/wallet-web/templates/default.conf.template
test/bdd/fixtures/wallet-web/docker-compose-web.yml

feat: Fetch the list of providers from Hub Auth and render on sign up page

---

.github/dependabot.yml

feat: added config file for Dependabot

---

cmd/wallet-web/src/pages/chapi/DIDAuth.vue
cmd/wallet-web/src/pages/chapi/DIDConnect.vue
cmd/wallet-web/src/pages/chapi/GetCredentials.vue
cmd/wallet-web/src/pages/chapi/MultipleQuery.vue
cmd/wallet-web/src/pages/chapi/PresentationDefQuery.vue
cmd/wallet-web/src/pages/chapi/QueryByFrame.vue
cmd/wallet-web/src/pages/chapi/Store.vue
cmd/wallet-web/src/pages/webWalletSamples.js

Fixes #753
Fixed chapi components layout. Since https://chapi-demo-issuer.digitalbazaar.com/ updated their layout, we had to adjust a few things.

fix: fixed chapi components layout

---

.github/dependabot.yml

feat: added test package.json to Dependabot config

---

cmd/wallet-web/tailwind.js

Related to #777
Added brand colors to the tailwind theme.

feat: added brand colors to tailwind theme

---

cmd/wallet-web/tailwind.js

Fixes #777 
Added brand gradients to tailwind theme in accordance with [the designs](https://share.goabstract.com/ce5af366-6808-470c-97c1-905a7e6d836d?collectionLayerId=faf96bb8-5092-45dc-9d06-043d29d21cec&mode=build).

feat: added brand gradients to tailwind theme

---

cmd/wallet-web/src/pages/chapi/Signup.vue
pkg/restapi/common/oidc/api.go
pkg/restapi/common/oidc/client.go
pkg/restapi/common/oidc/mock.go
pkg/restapi/oidc/operations.go

fix: Hydra login challenge cookie missing issue

---

test/bdd/fixtures/wallet-web/.env

chore: Update latest hub-auth

---

.gitattributes
cmd/wallet-web/src/assets/img/onboarding-bg-lg.svg
cmd/wallet-web/src/assets/img/onboarding-flare-lg.png
cmd/wallet-web/src/pages/chapi/Signup.vue
cmd/wallet-web/tailwind.js

This is not final page.  We have follow up issues to finalize the Sign-up page look
closes #766

feat: Implement background of the sign-in page and common layout using TrustBloc theme.

---

cmd/wallet-web/src/assets/img/onboarding-icon-1.svg
cmd/wallet-web/src/assets/img/onboarding-icon-2.svg
cmd/wallet-web/src/assets/img/onboarding-icon-3.svg
cmd/wallet-web/src/pages/chapi/Signup.vue
cmd/wallet-web/tailwind.js

feat: Add list icons and signup buttons using trustbloc margin theme.

---

cmd/wallet-web/src/assets/img/logo.png
cmd/wallet-web/src/assets/img/logo.svg
cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
cmd/wallet-web/src/pages/chapi/Login.vue
cmd/wallet-web/src/pages/chapi/Signup.vue

fix: Update Trustbloc logo

---

cmd/wallet-web/src/pages/chapi/Signup.vue
cmd/wallet-web/src/pages/layout/ContentFooter.vue

feat: Add dynamic footer year and reshuffle footer alignment for mobile screen as per UX design 

---

cmd/wallet-web/tailwind.js

Related to #801
Added common styles for buttons based on [the designs](https://share.goabstract.com/ce5af366-6808-470c-97c1-905a7e6d836d?collectionLayerId=8138ae3e-89a4-4f7c-b94e-1156122b9652&mode=build).

feat: added common styles for buttons

---

cmd/wallet-web/src/pages/layout/ContentFooter.vue

fix: changed footer id to a non-reserved value

---

cmd/wallet-web/src/pages/chapi/Signup.vue
test/bdd/fixtures/wallet-web/.env
test/bdd/fixtures/wallet-web/docker-compose-server.yml
test/bdd/fixtures/wallet-web/oidc-config/bdd_providers.yaml
test/bdd/fixtures/wallet-web/oidc-config/demo_providers.yaml
test/bdd/fixtures/wallet-web/static/images/demo_provider.svg

chore: Update edge-agent with latest hub-auth changes

---

cmd/wallet-web/src/assets/img/danger-icon.svg
cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/pages/chapi/Signup.vue
cmd/wallet-web/tailwind.js

Fixes #801 #825
Implemented structure and styles based on [the designs](https://share.goabstract.com/38b8cd5d-b961-4c2b-8fb6-7ed7134d6bc8?mode=build&sha=045b23df56d1146a7db77b8766a42a67a3cc5f79).

feat: created reusable styled component for input fields

---

cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/tailwind.js

Adjusted the fader to avoid overlapping, changed input color

fix: adjusted the fader

---

cmd/wallet-web/src/pages/chapi/Signup.vue

fix: added missing closing tags

---

.github/workflows/ci.yml

ci: Add npm login details in publish job

---

test/bdd/mock/demo-login-consent-server/templates/login.html

https://user-images.githubusercontent.com/7862595/125895013-7baed7b1-ff2b-459b-a129-5f701859c713.mp4
closes #811

feat: Login updated UX

---

.github/workflows/build.yml
.github/workflows/publish.yml

ci: publish job - build wallet web

---

test/bdd/fixtures/wallet-web/docker-compose-web.yml

test: remove unused container

---

images/wallet-server/Dockerfile
images/wallet-web/Dockerfile

chore: update docker manifest with new repo name

---

.github/workflows/build.yml

ci: log versions in publish job

---

cmd/wallet-web/src/assets/img/logo.svg
cmd/wallet-web/src/components/Logo/Logo.vue
cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
cmd/wallet-web/src/pages/Login.vue
cmd/wallet-web/src/pages/Signup.vue

feat: created reusable logo component

---

.github/workflows/build.yml

ci: publish - set lfs to true

---

cmd/wallet-web/src/main.js

fix: Login flow showing blank screen

---

docs/components/web_wallet.md

docs: webwallet doc updates

---

docs/components/web_wallet.md

docs: updated webwallet docs

---

docs/components/web_wallet.md

docs: fix invitation samples

---

cmd/wallet-web/src/main.js
cmd/wallet-web/src/pages/Signup.vue

fix: Temporary removing popup window to unblock sandbox

---

cmd/wallet-web/src/pages/DIDManagement.vue
cmd/wallet-web/src/pages/Login.vue
cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue

chore: refactored hrefs to lowercase, added missing changes

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

chore: removed parse-duration from /cmd/wallet-web/

---

cmd/wallet-server/startcmd/start.go
cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/LoginHandle.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/index.js
cmd/wallet-web/src/store/modules/user.js
test/bdd/mock/demo-login-consent-server/main.go

https://user-images.githubusercontent.com/7862595/127395301-43e7bcf9-3b52-4f97-992b-24f956ad76f4.mov

feat: Updated pop up window design using vuex

---

cmd/wallet-web/src/pages/Signup.vue

1. https://github.com/trustbloc/wallet/pull/882#discussion_r679187951 

fix: Address pop up watch window comment.

---

cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/store/modules/options.js

- router.push() instead of redirect
- initialize agent & load OIDC user only if after succesful user login

feat: login enhancements

---

.github/workflows/build.yml
cmd/wallet-web/alias.config.js
cmd/wallet-web/karma.conf.js
cmd/wallet-web/test/common.js
cmd/wallet-web/test/fixtures/agent-config.json
cmd/wallet-web/test/fixtures/docker-compose.yml
cmd/wallet-web/test/fixtures/testdata/prc-vc.json
cmd/wallet-web/test/fixtures/testdata/sample-presentation-1.json
cmd/wallet-web/test/fixtures/testdata/sample-presentation-2.json
cmd/wallet-web/test/fixtures/testdata/udc-bbs-vc.json
cmd/wallet-web/test/fixtures/testdata/udc-vc.json
cmd/wallet-web/test/specs/get.spec.js
cmd/wallet-web/test/specs/store.spec.js
cmd/wallet-web/vue.config.js
cmd/wallet-web/webpack.test.js

chore: enable wallet web unit test in CI

---

cmd/wallet-web/src/store/modules/options.js
pkg/restapi/common/store/cookie/store.go
pkg/restapi/oidc/operations.go
pkg/restapi/oidc/operations_test.go

- if cookie expiers in wallet-web, then ask user to signin
- if cookie expiers in wallet-server, then log and forward the signin request

fix: cookie issues

---

cmd/wallet-web/src/components/LocaleSwitcher/LocaleSwitcher.vue
cmd/wallet-web/src/pages/BlockNoAuth.vue
cmd/wallet-web/src/pages/Logout.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/router/index.js

Fixes #896
https://user-images.githubusercontent.com/33902374/128535916-cac7c591-669e-402f-98f8-486eb7fce7eb.mov

fix: fixed router history issue

---

.github/workflows/build.yml
Makefile

feat: added eslint and prettier checks to CI

---

cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/store/modules/user.js

fix: fixed issue with second time sign in/up

---

.github/workflows/build.yml

feat: added prettier and eslint to publish requirements

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

chore: removed sweetalert2 from /cmd/wallet-web

---

.github/dependabot.yml

fix: fixed path to ui automation package file

---

cmd/wallet-web/src/pages/DashboardV2.vue
cmd/wallet-web/src/pages/layout/DashboardLayoutV2.vue
cmd/wallet-web/src/router/routes.js

feat: added temporary path for the new dashboard

---

cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoader.vue
cmd/wallet-web/src/components/SkeletonLoader/VaultCard.vue
cmd/wallet-web/src/components/ToastNotification/ToastNotification.vue
cmd/wallet-web/src/pages/DashboardV2.vue
cmd/wallet-web/tailwind.js

https://user-images.githubusercontent.com/7862595/129115923-ea578293-992f-4d17-b5cb-96d862201cea.mp4
closes #928
#943 is created to address other two type credential and credential type

feat: Responsive vault card skeleton loader

---

test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/user-flow.js

Fixes #944
This PR also adds a fix to avoid switching the browser to non-existent window.

test: added automation test for localization logic

---

.github/dependabot.yml

feat: added new package files to Dependabot config

---

cmd/wallet-web/src/config/credentialDisplayData.json
cmd/wallet-web/src/pages/DashboardV2.vue

Purpose of this pr is to only remove the individual vue credential card component. Rest the design will be taken care in the follow up prs under credential detail story.  
Changes are made to v2 version of the dashboard. Please note friendly name will be taken care of as per the new design of the implementation. 
closes #936

feat: Update the existing credential cards components with config file

---

cmd/wallet-web/src/components/SidebarPluginV2/SideBarV2.vue
cmd/wallet-web/src/components/SidebarPluginV2/SidebarLinkV2.vue
cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/pages/DashboardV2.vue
cmd/wallet-web/tailwind.js

feat: added on hover styles to the new sidebar

---

scripts/run_ui_automation.sh

fix: add exit code for ui-automation

---

cmd/wallet-web/src/components/SidebarPlugin/Sidebar.vue
cmd/wallet-web/tailwind.js

feat: added underline styles to sidebar footer links

---

cmd/wallet-web/src/assets/img/credential--arrow-right-icon.svg
cmd/wallet-web/src/assets/img/credential--generic-icon.svg
cmd/wallet-web/src/assets/img/credential--school-icon.svg
cmd/wallet-web/src/config/credentialDisplayData.json
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/tailwind.js

feat: Add credential preview as per UX design

---

cmd/wallet-web/src/App.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/tailwind.js

Dashboard container is remain at the centered on different screen resolution

feat: Adding body shadows and credential detail layout for desktop

---

cmd/wallet-web/src/pages/Dashboard.vue
test/mock/demo-login-consent-server/templates/login.html

fix: Temporary fix for the credential preview and add random unique email for login

---

docs/components/wallet_web.md

docs: user preferences & did management

---

test/fixtures/wallet-web/.env
test/mock/demo-login-consent-server/main.go

chore: hub-auth update to hub-auth:0.1.7-snapshot-f9b282e

---

cmd/wallet-web/src/assets/img/icons-md--credentials-icon.svg
cmd/wallet-web/src/assets/img/icons-sm--chevron-down-icon.svg
cmd/wallet-web/src/assets/img/icons-sm--vault-icon.svg
cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/src/translations/Credentials/en.json
cmd/wallet-web/src/translations/Credentials/fr.json
cmd/wallet-web/src/translations/en.js
cmd/wallet-web/src/translations/fr.js
cmd/wallet-web/tailwind.js

svgs are optimized 
closes #972

feat: Add "No credentials yet" screen

---

cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/src/translations/Credentials/en.json
cmd/wallet-web/src/translations/Credentials/fr.json
cmd/wallet-web/tailwind.js

feat: Add the focus and responsive credential preview screen

---

cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/tailwind.js
test/mock/demo-login-consent-server/main.go

feat: No credential found screen mobile responsive and fix login bank issue

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/Get.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/pages/WACI.vue
cmd/wallet-web/src/pages/mixins/handler/waci.js
cmd/wallet-web/src/router/index.js

- added WACI redirect flow support
- closes #1006

feat: WACI redirect support in webwallet

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

chore: update to latest agent SDK

---

cmd/wallet-web/src/assets/img/more-icon.svg
cmd/wallet-web/src/components/DIDManagement/CreateOrb.vue
cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/Navbar/Navbar.vue
cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/components/TabbedInterface/Tabs.vue
cmd/wallet-web/src/pages/CredentialDetails.vue
cmd/wallet-web/src/pages/DIDManagement.vue
cmd/wallet-web/src/pages/Get.vue
cmd/wallet-web/src/pages/demos/WebWallet.vue
cmd/wallet-web/src/router/routes.js
cmd/wallet-web/src/translations/Credentials/en.json
cmd/wallet-web/src/translations/Credentials/fr.json
cmd/wallet-web/src/translations/en.js
cmd/wallet-web/src/translations/fr.js
cmd/wallet-web/tailwind.js

closes #1008 
Once the integration is done below will be layout. This layout is with static data input

feat: Reusable credential detail UI component layout

---

test/ui-automation/test/specs/credential-interaction-flow.js

test: chapi get vc feat

---

cmd/wallet-web/src/pages/PresentationDefQuery.vue

fix: didcomm flow - credential function name

---

cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/src/router/routes.js

feat: added routing logic for credential details screen

---

cmd/wallet-web/src/pages/mixins/common/helper.js

feat: Populate fallback properties with vc credential subject

---

cmd/wallet-web/src/pages/PresentationDefQuery.vue

fix: incorrect protocol handler reference in DIDComm flow

---

cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/tailwind.js

refactor: refined credential page styles, switched to useBreakpoints

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/pages/CredentialDetails.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/src/translations/CredentialDetails/en.json
cmd/wallet-web/src/translations/CredentialDetails/fr.json
cmd/wallet-web/src/translations/Credentials/en.json
cmd/wallet-web/src/translations/Credentials/fr.json
cmd/wallet-web/src/translations/en.js
cmd/wallet-web/src/translations/fr.js

feat: implemented credential details banner component

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

chore: update agent-sdk dependency

---

cmd/wallet-web/src/pages/CredentialDetails.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/mixins/common/helper.js
cmd/wallet-web/src/store/modules/user.js

closes #1017 
Manifested 
Generic credential 
https://user-images.githubusercontent.com/7862595/132024658-3021afc9-f810-4667-80de-5cd73755eedb.mov

feat: Integrate credential details screen with the processed credential array

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/config/credentialDisplayData.js
cmd/wallet-web/src/pages/CredentialDetails.vue
cmd/wallet-web/src/pages/mixins/common/helper.js

feat: integrated credential details banner with real data

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/components/Navbar/Navbar.vue
cmd/wallet-web/src/pages/CredentialDetails.vue

fix: fixed navbar height issue, implemented mobile design

---

cmd/wallet-web/src/store/modules/options.js
test/fixtures/wallet-web/docker-compose-web.yml

chore: disable remote context download for wallet agent wasm

---

cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
cmd/wallet-web/src/pages/Dashboard.vue

refactor: created reusable component for credential preview

---

cmd/wallet-web/src/pages/mixins/common/helper.js
cmd/wallet-web/src/pages/mixins/common/presentationExchange.js
cmd/wallet-web/test/fixtures/testdata/contexts/agent-startup-contexts.json
cmd/wallet-web/test/specs/presexch.spec.js

feat: js schema-uri matching now parses json-ld contexts for cred type IDs

---

cmd/wallet-web/src/config/credentialDisplayData.js

feat: Add manifest for CMTR  and crude Product oil credentials

---

cmd/wallet-web/src/assets/img/credential--arrow-right-icon-light.svg
cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
cmd/wallet-web/src/config/credentialDisplayData.js
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/mixins/common/helper.js
cmd/wallet-web/tailwind.js

Fixes #1051 
https://user-images.githubusercontent.com/33902374/132898404-70d5ba16-ef4f-457a-a2bf-619f0ff04a78.mov

feat: added brand colors, hover and focus states to credential preview

---

cmd/wallet-web/src/assets/img/credential--flight-icon.svg
cmd/wallet-web/src/assets/img/credential--school-icon.svg
cmd/wallet-web/src/assets/img/credential--uscis-icon.svg
cmd/wallet-web/src/assets/img/credential--vaccination-icon.svg
cmd/wallet-web/src/assets/img/credential-drivers-license-icon.svg
cmd/wallet-web/src/config/credentialDisplayData.js
cmd/wallet-web/src/config/supportedLocales.js

feat: added authentic icons to supported types of credentials

---

cmd/wallet-web/src/pages/WACIShare.vue

added 1 second delay for now to avoid issue of present proof msg not
getting delivered

fix: waci integration issue

---

cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue

feat: disable CHAPI for mobile browsers

---

cmd/wallet-web/alias.config.js
cmd/wallet-web/src/assets/img/generic-issuer-icon.svg
cmd/wallet-web/src/assets/img/share.svg
cmd/wallet-web/src/assets/img/small-lock-icon.svg
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/pages/DIDAuth.vue
cmd/wallet-web/src/pages/Get.vue
cmd/wallet-web/src/router/routes.js
cmd/wallet-web/tailwind.js

closes #1045
Reading external URLs will be handled in this PR #1055 
Svgs are optimized 

feat: Chapi DID Auth updated UI

---

cmd/wallet-web/.gitignore
cmd/wallet-web/public/favicon.png
cmd/wallet-web/public/index.html
cmd/wallet-web/public/logo.png
cmd/wallet-web/src/components/Logo/Logo.vue

chore: updated favicon

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/pages/CredentialDetails.vue
cmd/wallet-web/src/router/routes.js

feat: added brand colors and dynamic icons to credential details banner

---

Makefile
cmd/wallet-web/src/config/credentialDisplayData.js
cmd/wallet-web/src/pages/demos/webWalletSamples.js
test/ui-automation/test/specs/credential-interaction-flow.js

- Add friendly names
- Add logo
- Add colour
closes #1069 

chore: Configure Booking reference VC

---

cmd/wallet-web/src/pages/WACIShare.vue

chore: increase WACI share wait before redirect

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/src/translations/CredentialDetails/en.json
cmd/wallet-web/src/translations/CredentialDetails/fr.json
cmd/wallet-web/tailwind.js

https://user-images.githubusercontent.com/7862595/133180120-2c11ac82-ffa6-4043-84fa-f051fb165225.mov
closes #1061

feat: Chapi save credentials UI change

---

.github/workflows/build.yml
.github/workflows/publish.yml

ci: increase publish job timeout

---

cmd/wallet-web/src/assets/img/icons-warning.svg
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/MultipleQuery.vue
cmd/wallet-web/src/translations/CHAPI/en.json
cmd/wallet-web/src/translations/CHAPI/fr.json
cmd/wallet-web/src/translations/en.js
cmd/wallet-web/src/translations/fr.js
cmd/wallet-web/test/specs/get.spec.js

feat: implemented new designs for chapi share page

---

cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoader.vue
cmd/wallet-web/src/components/SkeletonLoader/VaultCard.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/tailwind.js

fix: fixed skeleton loader width issue

---

cmd/wallet-web/public/manifest.json
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/store/modules/user.js
test/ui-automation/wdio.conf.js

fix: blank dashboard during re-login

---

cmd/wallet-web/src/pages/MultipleQuery.vue
cmd/wallet-web/src/pages/WACIShare.vue

feat: updated waci share component with the new designs

---

cmd/wallet-web/src/config/credentialDisplayData.js
cmd/wallet-web/src/pages/MultipleQuery.vue
cmd/wallet-web/src/pages/mixins/common/helper.js

feat: implemented new design for credential details in CHAPI share flow

---

cmd/wallet-web/src/config/credentialDisplayData.js
cmd/wallet-web/src/pages/MultipleQuery.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/pages/mixins/common/helper.js

feat: implemented new design for credential details in WACI share flow

---

cmd/wallet-web/src/pages/WACIShare.vue

refactor: adjust waci share for rendering outside of iframe

---

cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/router/routes.js
cmd/wallet-web/src/store/modules/user.js

- redirect to signin, not signup
- disable chapi handler registration

feat: WACI redirect enhancements

---

cmd/wallet-web/src/pages/WACIShare.vue

fix: WACI integration issues

---

test/fixtures/wallet-web/.env
test/fixtures/wallet-web/docker-compose-web.yml

chore: update bdd test images to release

---

cmd/wallet-web/src/pages/Signin.vue

fix: query params for signin redirect

---

cmd/wallet-web/src/pages/Store.vue

fix: Fix the background colour change issue in save credential

---

cmd/wallet-web/src/pages/WACIShare.vue

https://user-images.githubusercontent.com/33902374/133644746-f6417f7e-f570-45d6-be10-23d296ebdbb0.mov

fix: fixed waci share layout

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/fixtures/wallet-web/.env

chore: update to latest agent-sdk-web and wallet-sdk

---

.github/workflows/publish.yml

ci: add lfs tag to release build

---

cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/test/specs/store.spec.js

fix: Refactor toggle solution in store vue

---

cmd/wallet-web/src/pages/Store.vue

Fixes #1104
https://user-images.githubusercontent.com/33902374/134076541-16b9b79b-0530-406c-bca0-1046b8be638f.mov

fix: fixed CHAPI store height issue

---

cmd/wallet-web/src/components/DIDManagement/Preferences.vue
cmd/wallet-web/src/components/Spinner/Spinner.vue
cmd/wallet-web/src/components/StyledButton/StyledButton.vue
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/tailwind.js

Fixes #1114
Updated spinner, created reusable component for styled button & defined loading state for it

feat: added success message and more

---

Makefile
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js

test: [ui-automation] credential details screen

---

.github/workflows/build.yml
.github/workflows/publish.yml
Makefile

ci: push wallet-server before wallet-web

---

test/ui-automation/babel.config.js
test/ui-automation/package-lock.json
test/ui-automation/package.json
test/ui-automation/test/helpers/index.js
test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/wdio.conf.js
test/ui-automation/wdio.shared.conf.js

test: [ui-automation] support for ES modules

---

test/mock/demo-login-consent-server/templates/login.html

fix: Add the spinner to the button click

---

cmd/wallet-web/src/pages/BlockNoAuth.vue
cmd/wallet-web/src/router/routes.js

refactor: refactored BlockNoAuth component

---

test/ui-automation/test/specs/waci-flow.js

test: waci-share - validate credential details

---

cmd/wallet-web/src/pages/PresentationDefQuery.vue

Since we don't have any manifested issuers to support, we don't need to run them against the jpquery

fix: potential fix for issuers not showing up in DIDComm share flow component

---

cmd/wallet-web/src/pages/PresentationDefQuery.vue
cmd/wallet-web/src/pages/mixins/get/getCredentialsByQuery.js

fix: removed selectedVCs parameter as it's not used anymore

---

cmd/wallet-web/src/assets/img/icons-sm--plus-icon.svg
cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
cmd/wallet-web/src/components/VaultCard/VaultCard.vue
cmd/wallet-web/src/pages/PageNotFound.vue
cmd/wallet-web/src/pages/PresentationDefQuery.vue
cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/translations/Vaults/en.json
cmd/wallet-web/src/translations/Vaults/fr.json
cmd/wallet-web/tailwind.js

feat: Refactor vault card mobile and desktop , Add default vault and address warnings

---

cmd/wallet-web/src/pages/mixins/common/register.js

chore: add log msg

---

cmd/wallet-web/src/pages/mixins/common/register.js

fix: check equivalent id array length

---

cmd/wallet-web/src/pages/mixins/common/register.js

fix: equivalentId array check

---

cmd/wallet-web/src/store/modules/options.js

fix: mediator issues in dev mode

---

cmd/wallet-web/src/assets/img/Icons-sm--close-icon.svg
cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/components/Modal/AddVault.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Dashboard.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/src/translations/Vaults/en.json
cmd/wallet-web/src/translations/Vaults/fr.json
cmd/wallet-web/tailwind.js

https://user-images.githubusercontent.com/7862595/141301487-04bfa7b3-ee22-49f0-a13a-b5516064f400.mov
https://user-images.githubusercontent.com/7862595/141301577-2b064e1b-a8ec-49d5-826c-6452beabb92a.mov
closes #1183  #1209 #1210

feat: Add vault implementation

---

cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/translations/CredentialDetails/fr.json

closes #1202 
https://user-images.githubusercontent.com/7862595/141383999-caeaee18-5f98-48b9-9202-bb4ffec9b6b4.mov

fix: Fix the French name rendering issue for All Vault in credential

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/store/modules/options.js

feat: add unanchoredDIDMaxLifeTime flag

---

cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/pages/Vaults.vue

fix: Refactor Fetch All Vault logic

---

cmd/wallet-web/src/components/DIDManagement/CreateOrb.vue
cmd/wallet-web/src/components/DIDManagement/ImportDid.vue
cmd/wallet-web/src/components/DIDManagement/Preferences.vue

fix: getAllDID returning uninform data

---

cmd/wallet-web/src/pages/DIDAuth.vue
cmd/wallet-web/src/pages/MultipleQuery.vue
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/src/pages/mixins/handler/chapi.js

fix: use raw value with web workers api

---

docs/dev/dev-mode.md
docs/test/test.md
test/fixtures/wallet-web/mysql-config/mysql_config.sql

docs: update repo name in the documentation

---

cmd/wallet-web/src/components/CustomSelect/CustomSelect.vue
cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/components/Modal/AddVault.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/pages/mixins/common/register.js
cmd/wallet-web/src/translations/Vaults/en.json
cmd/wallet-web/src/translations/Vaults/fr.json

closes #1232 #1215
https://user-images.githubusercontent.com/7862595/142199580-0e6cb6be-09a9-4bed-9e52-c0b0894e789b.mov

feat: Link save credentials with Vault

---

Makefile
cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/test/common.js
cmd/wallet-web/test/specs/get.spec.js
cmd/wallet-web/test/specs/store.spec.js
cmd/wallet-web/webpack.test.js
test/ui-automation/package-lock.json
test/ui-automation/package.json

refactor: updated unit tests setup

---

test/ui-automation/package-lock.json
test/ui-automation/package.json

chore: upgraded ui automation deps

---

cmd/wallet-web/src/components/Modal/AddVault.vue

feat: added error handling for add vault logic

---

cmd/wallet-web/src/components/CustomSelect/CustomSelect.vue
cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/Navbar/NavbarLink.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/pages/PageNotFound.vue
cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/pages/layout/DashboardLayout.vue
cmd/wallet-web/src/router/routes.js
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/test/specs/waci-flow.js

refactor: renamed dashboard screen to credentials, set vaults as default route

---

cmd/wallet-web/src/pages/Store.vue

fix: Fix the selected default in the dropdown to save cred in default cred

---

cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/pages/Vaults.vue

closes #1256
https://user-images.githubusercontent.com/7862595/144285779-2e9d54a3-9952-4699-b33f-30ba15ea97de.mov

feat: Link Vault with credential screen

---

cmd/wallet-web/src/components/Modal/AddVault.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Vaults.vue

Fixes #1259
https://user-images.githubusercontent.com/33902374/144307605-62efc3bc-b3d4-403e-bd95-2f0ddf5f755a.mov

feat: refresh vaults when the new one is created

---

cmd/wallet-web/src/components/Navbar/Navbar.vue
cmd/wallet-web/src/components/Navbar/NavbarLink.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/translations/Credentials/en.json
cmd/wallet-web/src/translations/Credentials/fr.json

Fixes #1277
Fixes #1282
https://user-images.githubusercontent.com/33902374/144712348-07c1847f-ad7d-4249-a5bf-24cb31b05b7c.mov

feat: dynamically update vault name in credentials screen

---

cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/pages/Vaults.vue

fix: Adding id as prop to default and vault flyout menus

---

cmd/wallet-web/scripts/setup_test.sh
cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
cmd/wallet-web/src/pages/CredentialDetails.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/store/modules/user.js
scripts/wallet_web_dev_start.sh
test/ui-automation/test/specs/credential-interaction-flow.js

Fixes #1279
https://user-images.githubusercontent.com/33902374/144755189-bb99450f-c945-4db8-9629-a69568283b73.mov
Fixes #1294
https://user-images.githubusercontent.com/33902374/145117838-517a0e43-3bc8-4183-9c1e-10b5accd7b03.mov

feat: display credentials per vaults in credentials screen

---

cmd/wallet-web/src/store/modules/user.js

feat: added selected vault and credential ids to vuex store

---

cmd/wallet-web/src/components/Modal/Modal.vue
cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Vaults.vue

closes #1311  
https://user-images.githubusercontent.com/7862595/146083608-5f395e19-c8dc-4a50-8f56-0ef5d9f0fc3f.mov

feat: Enhance closing logic for the modal component

---

cmd/wallet-web/src/components/AppLink/AppLink.vue
cmd/wallet-web/src/components/Flyout/Flyout.vue
cmd/wallet-web/src/components/Modal/Modal.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/store/modules/options.js
cmd/wallet-web/src/store/modules/user.js

Fixes #1270
Fixes #1329
Fixes #1286
Finalizes vaults filters, implements reusable extended link component (aka `AppLink`), refactors vault card. In addition, refactored `Credentials.vue` to use `Composition API` approach.
https://user-images.githubusercontent.com/33902374/146206444-c3118a17-a520-4bba-9025-67cd19af88f9.mov

feat: sync vault filter selection with store, add extended link reusable component, refactor vault card

---

test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js

chore: added test for delete credential back

---

cmd/wallet-web/package.json
cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
cmd/wallet-web/src/layouts/WACI.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/translations/CHAPI/en.json
cmd/wallet-web/src/translations/CHAPI/fr.json
cmd/wallet-web/src/utils/mixins/handler/waci.js

- support for WACI `streamlined-vc` oob goal code
- for now using makeshift credential save UI
- pending items listed in #1336
- Closes #1321

feat: WACI issuance implementation

---

cmd/wallet-web/src/components/Modal/Modal.vue
cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/translations/Vaults/en.json
cmd/wallet-web/src/translations/Vaults/fr.json

https://user-images.githubusercontent.com/7862595/146404759-2a949744-784a-47b2-a2b0-5a73a2e3da6a.mov
closes #1314

feat: Add Rename Vault feature

---

cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue

fix: Incorrect UI alignment with Multiple OIDC providers

---

cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue
test/fixtures/wallet-web/.env
test/fixtures/wallet-web/oidc-config/demo_providers.yaml
test/fixtures/wallet-web/static/images/demo_provider.svg
test/fixtures/wallet-web/static/images/signin_logo.svg
test/fixtures/wallet-web/static/images/signup_logo.svg
test/ui-automation/test/helpers/wallet.js

closes #1358
Images are svg optimized

fix: Update signinText and signuptext to logo Url in oidc config

---

cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue

https://user-images.githubusercontent.com/7862595/146996314-d3e5571a-ab8f-4861-9e93-3e4c446e0c34.mp4
closes #1362

feat: Support to set the order for odic providers

---

cmd/wallet-web/src/assets/img/icons-checkmark.svg
cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/translations/Vaults/en.json
cmd/wallet-web/src/translations/Vaults/fr.json
cmd/wallet-web/tailwind.js

Fixes #1208 
Fixes #1320
Fixes #1207
https://user-images.githubusercontent.com/33902374/147004258-00444741-116b-48b1-98f2-dbbcf8760bff.mov

feat: input field validation for add vault modal

---

test/mock/adapter/adapter.go
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/test/specs/waci-issuance-flow.js

feat: WACI issuance test - user not signed in

---

test/fixtures/wallet-web/.env

chore: hub-auth docker update

---

cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Vaults.vue

Fixes #1359
As mentioned by the design team, we are trimming any leading/trailing whitespaces, as well as removing duplicate whitespaces in a row.
https://user-images.githubusercontent.com/33902374/147355914-3c3ed626-1e57-4370-9d65-a640e117a02a.mov

feat: added validation against existing vaults names

---

cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
cmd/wallet-web/src/pages/Vaults.vue

closes #1384 #1379
Signed-off-by: talwinder50 <talwinder.kaur@securekey.com>
https://user-images.githubusercontent.com/7862595/147695557-c75a68ef-23ad-45ee-b8e7-f3d39e2ba800.mp4

feat: Disable delete for the last vault and fix rename modal bug

---

cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/layouts/WACI.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/router/routes.js
cmd/wallet-web/src/translations/CHAPI/en.json
cmd/wallet-web/src/translations/CHAPI/fr.json
cmd/wallet-web/tailwind.js

A part of #1319 
https://user-images.githubusercontent.com/33902374/147690568-eeea45df-58b2-4b6e-a2b2-6b4364fa6551.mov

feat: updated WACI Share UI to the new designs

---

cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/pages/Vaults.vue
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/vault-interaction-flow.js

feat: Add Automation test for Add Vault

---

cmd/wallet-web/src/components/InputField/InputField.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Vaults.vue
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/vault-interaction-flow.js
test/ui-automation/wdio.shared.conf.js

test: Add Vault Automation test

---

cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/translations/Vaults/fr.json
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/vault-interaction-flow.js
test/ui-automation/wdio.conf.js

test: Add support for locale and Spacing scenarios

---

test/fixtures/wallet-web/.env

chore: hub-auth update

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/components/WACI/CredentialBanner.vue
cmd/wallet-web/src/components/WACI/CredentialPreview.vue
cmd/wallet-web/src/pages/MultipleQuery.vue
cmd/wallet-web/src/pages/PresentationDefQuery.vue
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/utils/mixins/common/helper.js

feat: created reusable component for WACI Share credential preview

---

cmd/wallet-web/src/pages/WACIShare.vue

fix: fixed error handling for missing credentials, i18n pluralization

---

cmd/wallet-web/src/assets/img/icons-circle-check.svg
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/translations/WACI/en.json
cmd/wallet-web/src/translations/WACI/fr.json
cmd/wallet-web/src/translations/en.js
cmd/wallet-web/src/translations/fr.js
test/ui-automation/test/specs/waci-share-flow.js

Fixes #1416 
https://user-images.githubusercontent.com/33902374/149578147-67c0efaa-90fa-4657-9cad-d5aa443f7e0a.mov
https://user-images.githubusercontent.com/33902374/149578493-b98e6e02-fcb2-4eb1-b895-863cdf486b3f.mov

feat: added success screen for WACI Share flow

---

cmd/wallet-web/src/components/WACI/CredentialOverview.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/translations/WACI/en.json
cmd/wallet-web/src/translations/WACI/fr.json

fix: added missing translation, cleaned up

---

cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
cmd/wallet-web/src/components/WACI/CredentialOverview.vue
cmd/wallet-web/src/components/WACI/WACIActionButtonsContainer.vue
cmd/wallet-web/src/components/WACI/WACICredentialsMissing.vue
cmd/wallet-web/src/components/WACI/WACIError.vue
cmd/wallet-web/src/components/WACI/WACILoading.vue
cmd/wallet-web/src/components/WACI/WACISharing.vue
cmd/wallet-web/src/components/WACI/WACISuccess.vue
cmd/wallet-web/src/layouts/WACI.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/translations/WACI/en.json
cmd/wallet-web/src/translations/WACI/fr.json
test/ui-automation/test/specs/waci-issuance-flow.js

Fixes #1399 
https://user-images.githubusercontent.com/33902374/149846836-4c0b32fd-2c83-4897-af33-85d32f0c2f59.mov
https://user-images.githubusercontent.com/33902374/149846847-bee7405b-f825-4152-b01a-360c7aa8425f.mov

feat: updated WACI Issue UI

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

chore: updated to latest agent-sdk

---

cmd/wallet-web/src/pages/WACIIssue.vue

https://user-images.githubusercontent.com/33902374/150000435-de20ae03-d3f1-444a-9702-f4f0814570eb.mov

fix: fixed an issue waci issuance flow

---

test/ui-automation/test/helpers/chapi.js

fix: adjusted chapi automation test

---

cmd/wallet-web/src/assets/img/credential-icon-colored.svg
cmd/wallet-web/src/assets/img/vault-icon-colored.svg
cmd/wallet-web/src/components/Vaults/WelcomeBanner.vue
cmd/wallet-web/src/pages/Credentials.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/translations/Vaults/en.json
cmd/wallet-web/src/translations/Vaults/fr.json

Fixes #1401
Check [this full flow video](https://securekeytechnologies-my.sharepoint.com/:v:/g/personal/anton_biriukov_securekey_com/Eaahy7xDAwhFnEAJi_PJMKQBil5_c0IJs-HYWr_gjOLA-g?e=ajFbGP) for more details.

feat: implemented welcome message banner

---

.github/workflows/build.yml
.github/workflows/publish.yml
Makefile
cmd/wallet-server/go.mod
go.mod
test/mock/adapter/go.mod
test/mock/demo-login-consent-server/go.mod

chore: golang v1.17 update

---

.github/workflows/build.yml
.github/workflows/publish.yml

chore: upgraded alpine version to 3.15 in publish jobs

---

cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/Logo/Logo.vue
cmd/wallet-web/src/components/Navbar/Navbar.vue

feat: added link to vaults in navbar logo

---

cmd/wallet-server/go.mod
cmd/wallet-server/go.sum
cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/Navbar/Navbar.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/components/Vaults/WelcomeBanner.vue
cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
cmd/wallet-web/src/layouts/WACI.vue
cmd/wallet-web/src/pages/Signin.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/pages/Vaults.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/test/fixtures/.env
go.mod
go.sum
scripts/check_unit.sh
test/mock/adapter/go.mod
test/mock/adapter/go.sum

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

chore: update latest afgo and agent-sdk

---

cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
cmd/wallet-web/src/components/Header/Header.vue
cmd/wallet-web/src/components/WACI/CredentialBanner.vue
cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
cmd/wallet-web/src/components/WACI/CredentialOverview.vue
cmd/wallet-web/src/layouts/WACI.vue
cmd/wallet-web/src/layouts/WACIShareLayout.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/pages/WACIShareOverview.vue
cmd/wallet-web/src/router/routes.js
cmd/wallet-web/src/translations/CHAPI/en.json
cmd/wallet-web/src/translations/CHAPI/fr.json
cmd/wallet-web/src/translations/WACI/en.json
cmd/wallet-web/src/translations/WACI/fr.json

Fixes #1391
https://user-images.githubusercontent.com/33902374/152052405-b13e3c39-5344-406b-b92c-28d59970eaa4.mov

feat: implemented UI for sharing multiple credentials in WACI

---

test/ui-automation/wdio.shared.conf.js

test: disable vault-test to unblock build failure

---

scripts/run_ui_automation.sh

- add healthchecks
- reduce sleep time before running healthchecks
- reduce # of retries for healthcheck
- reduce sleep time between healthchecks

test: add component healthchecks before running tests

---

cmd/wallet-web/src/components/Modal/Modal.vue
cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/VaultCard.vue
cmd/wallet-web/src/pages/Signup.vue
cmd/wallet-web/src/pages/Vaults.vue
images/wallet-web/templates/default.conf.template
scripts/run_ui_automation.sh
test/ui-automation/package-lock.json
test/ui-automation/package.json
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/test/specs/vault-interaction-flow.js
test/ui-automation/test/specs/waci-issuance-flow.js
test/ui-automation/test/specs/waci-share-flow.js
test/ui-automation/wdio.shared.conf.js

feat: optimized automation tests

---

test/ui-automation/wdio.shared.conf.js

chore: incresed waitFor timeout in automation tests

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/fixtures/wallet-web/docker-compose-web.yml

fix: enable webkms for wallet

---

cmd/wallet-web/src/config/credential-output-descriptors.json

- added credential manifests for vaccination certificate, booking
reference & mDL

chore: manifests for demo VCs

---

cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
cmd/wallet-web/src/pages/Vaults.vue
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/vault-interaction-flow.js

feat: added automation tests for rename a vault flow

---

cmd/wallet-web/src/components/Modal/Modal.vue
cmd/wallet-web/src/pages/Vaults.vue
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/vault-interaction-flow.js
test/ui-automation/wdio.shared.conf.js

test: added automation test for removing vaults

---

cmd/wallet-web/src/components/Signout/Signout.vue
cmd/wallet-web/src/layouts/DashboardLayout.vue
cmd/wallet-web/src/pages/Vaults.vue
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/test/specs/vault-interaction-flow.js
test/ui-automation/test/specs/waci-issuance-flow.js
test/ui-automation/test/specs/waci-share-flow.js

test: validate welcome banner dismissal

---

cmd/wallet-web/src/pages/Vaults.vue

feat: updated vaults screen to use metadata endpoints

---

cmd/wallet-web/src/store/modules/options.js
test/mock/adapter/didcomm.go

fix: media profile default value

---

cmd/wallet-web/src/mixins/get/didConn.js
cmd/wallet-web/src/mixins/get/getCredentialsByQuery.js

fix: blindedrouter flag

---

cmd/wallet-web/src/config/credential-output-descriptors.json

chore: default manifests - fixing prc image schema

---

test/fixtures/wallet-web/.env
test/fixtures/wallet-web/docker-compose-server.yml
test/fixtures/wallet-web/docker-compose-web.yml

test: remove unused docker containers

---

test/fixtures/wallet-web/.env

test: trustbloc docker dep update

---

test/fixtures/wallet-web/.env
test/ui-automation/wdio.shared.conf.js

chore: trustbloc auth and router docker version update

---

scripts/run_ui_automation.sh

chore: increase healthcheck sleep time

---

test/mock/adapter/adapter.go
test/mock/adapter/templates/verifier/waci-verifier.html
test/ui-automation/wdio.conf.js

- Remove hardcoded Presentation Exchange (PEx) query and added it to html to support dynamic update
closes #1546 

test: [waci-share] Support to dynamically add Presentation Exchange (PEx)

---

test/fixtures/wallet-web/docker-compose-demo.yml
test/mock/adapter/adapter.go
test/mock/adapter/templates/verifier/oidc-verifier.html
test/ui-automation/test/specs/waci-flow.js

- Add a button to trigger oidc4vp flow
- Construct auth-req with claims as TODO
- Add callback handler with vp validation as TODO
part of #1529 

test: oidc4vp demo setup

---

cmd/wallet-web/src/layouts/OIDC.vue
cmd/wallet-web/src/layouts/OIDCShareLayout.vue
cmd/wallet-web/src/pages/OIDCShare.vue
cmd/wallet-web/src/pages/OIDCShareOverview.vue
cmd/wallet-web/src/router/routes.js

* Add a new route
* New vue page (for now, copy WACI share page)
* Extract PEx from claims query param
* Run a search through existing VCs in Wallet (use existing API)
* Show preview/consent screen (use existing API)
* redirect
closes #1527
https://user-images.githubusercontent.com/2052394/158216430-9bd9c880-b004-4924-bbac-2b21b6efffcd.mov

chore: OIDC share (Route, read claims and VCS Search)

---

test/ui-automation/test/specs/waci-flow.js

test: [waci] validate saved credential

---

cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue

fix: Icons are not loading in credential list page

---

cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
cmd/wallet-web/src/layouts/OIDC.vue
cmd/wallet-web/src/pages/OIDCShare.vue
cmd/wallet-web/src/router/routes.js
test/mock/adapter/adapter.go
test/mock/adapter/templates/verifier/oidc-verifier.html

- Changing routes to /oidc/share
- Populating data without hardcoding
- Adding state, vp_token and id_token params to response
Closes #1562 
Closes #1560 
https://user-images.githubusercontent.com/2052394/159281611-4eb00cfa-b334-46ad-9b9c-168cc568cd08.mov
Part of #1563

chore: Populating details in OIDC Share and passing "state" and token params

---

cmd/wallet-web/src/components/CredentialDetails/Banner.vue
cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
cmd/wallet-web/src/components/WACI/CredentialBanner.vue
cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
cmd/wallet-web/src/components/WACI/CredentialOverview.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue
cmd/wallet-web/src/translations/WACI/en.json

Fixes #1518
Fixes #1564
Fixes #1583
https://user-images.githubusercontent.com/33902374/158299830-2a71793f-6378-443e-90bc-795c24188513.mov
https://user-images.githubusercontent.com/33902374/159367717-46940724-55d0-42f0-88e4-bc187aabda25.mov
https://user-images.githubusercontent.com/33902374/159367737-4ffcc45f-747e-4f23-afd9-8e3c5205fb94.mov
Note: credentials screen is still broken after 

feat: added support for DWC in WACI Issue, Store and updated credentials screen

---

test/fixtures/wallet-web/static/config/credential-output-descriptors.json

Output descriptor file in config folder similar to https://github.com/trustbloc/wallet/tree/main/test/fixtures/wallet-web/static/config

chore: add dynamic wallet credential manifest

---

test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/test/specs/oidc-flow.js
test/ui-automation/wdio.conf.js
test/ui-automation/wdio.shared.conf.js

test: oidc-share automation test setup

---

cmd/wallet-web/src/pages/OIDCShare.vue
cmd/wallet-web/src/pages/WACIShare.vue

closes #1608
https://user-images.githubusercontent.com/7862595/160029319-bb182391-af4e-41a1-ac7a-26e7675006a1.mov
https://user-images.githubusercontent.com/7862595/160029408-d8e72e51-fd60-4eaf-b5fe-4468aae3c96a.mov

fix: WACI share shows missing credential page before sharing credential

---

cmd/wallet-web/karma.conf.js
cmd/wallet-web/src/pages/Store.vue
cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json

Fixes #1517
https://user-images.githubusercontent.com/33902374/160257078-c1b090a0-fbe4-4a38-bb15-85ea2d1b2150.mov

feat: updated CHAPI Store to support DWC

---

cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
cmd/wallet-web/src/components/CredentialDetails/RenameCredentialModal.vue
cmd/wallet-web/src/components/DIDManagement/Preferences.vue
cmd/wallet-web/src/components/Modal/Modal.vue
cmd/wallet-web/src/components/StyledButton/StyledButton.vue
cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
cmd/wallet-web/src/components/WACI/WACICredentialsMissing.vue
cmd/wallet-web/src/components/WACI/WACIError.vue
cmd/wallet-web/src/components/WACI/WACISuccess.vue
cmd/wallet-web/src/pages/BlockNoAuth.vue
cmd/wallet-web/src/pages/OIDCShare.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue

fix: fixed issue with certain button styles not applying

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/OIDCShare.vue
cmd/wallet-web/src/pages/WACIIssue.vue
cmd/wallet-web/src/pages/WACIShare.vue

Fixes #1410 
https://user-images.githubusercontent.com/33902374/160256630-991b9fb1-8e19-40ca-a008-8ad0e0f26bfb.mov
https://user-images.githubusercontent.com/33902374/160256638-9141ee0b-de61-428d-bd4d-611b499631cb.mov
https://user-images.githubusercontent.com/33902374/160256593-c4059fad-d098-4a19-8763-787ef9446775.mov

feat: enabled vault name in WACI/OIDC share flows

---

cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue

fix: Background of the icon was missing

---

cmd/wallet-web/src/pages/OIDCShare.vue
test/mock/adapter/adapter.go
test/mock/adapter/common.go

Creates the basic flow for VP_Token in OIDC Share
Closes #1563
https://user-images.githubusercontent.com/2052394/160202339-0e1e5484-f5a1-4360-ac7e-f376725fad58.mov

chore: VP Token generation OIDC Share

---

cmd/wallet-web/src/layouts/OIDC.vue
cmd/wallet-web/src/layouts/OIDCInitiateLayout.vue
cmd/wallet-web/src/layouts/OIDCSaveLayout.vue
cmd/wallet-web/src/mixins/index.js
cmd/wallet-web/src/mixins/oidc/oidc.js
cmd/wallet-web/src/pages/OIDCSave.vue
cmd/wallet-web/src/router/routes.js
test/mock/adapter/adapter.go
test/mock/adapter/go.mod
test/mock/adapter/main.go
test/mock/adapter/templates/issuer/issuer.html
test/mock/adapter/templates/issuer/oidc-issuer.html
test/mock/adapter/templates/issuer/oidc-login.html
test/mock/adapter/templates/verifier/oidc-verifier.html

Added basic implementation for initiate issuance & authorize flow.
Updated mock issuer to support initiate issuance, authorize & login
- Closes #1588
- Closes #1589
- Closes #1629

feat: OIDC4vci in wallet - initiate issuance & authorize

---

test/ui-automation/package-lock.json
test/ui-automation/package.json
test/ui-automation/test/helpers/chapi.js

test: chrome-driver v100

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/layouts/OIDC.vue
cmd/wallet-web/src/layouts/OIDCSaveLayout.vue
cmd/wallet-web/src/mixins/oidc/oidc.js
cmd/wallet-web/src/pages/OIDCSave.vue
cmd/wallet-web/src/router/routes.js
test/mock/adapter/adapter.go
test/mock/adapter/templates/issuer/oidc-issuer.html

- implemented token request flow
- implemented credential request flow
- state management between initiate issuance & callback to wallet
- added mock implementation
- Closes #1635
- Closes #1590
- Closes #1634

feat: oidc4vci - token & credential request flow

---

test/mock/adapter/templates/issuer/oidc-login.html
test/ui-automation/test/specs/oidc-flow.js
test/ui-automation/wdio.conf.js

chore: UI automation tests for OIDC issuance

---

test/ui-automation/test/specs/oidc-flow.js

chore: coverage for OIDC4VCI multiple credential flow

---

.github/dependabot.yml

refactor: enabled automatic rebasing for dependabot PRs

---

.github/workflows/build.yml

ci: add pr condition for semantic pr check

---

cmd/wallet-web/src/layouts/GetLayout.vue
cmd/wallet-web/src/pages/CHAPISharePage.vue

Closes #1672 
- renamed `PresentationDefQueryPage.vue` -> `CHAPISharePage.vue`
- refactored the component to use the Composition API and the setup script

refactor: refactored PresentationDefQueryPage -> CHAPISharePage

---

cmd/wallet-web/src/layouts/OIDCInitiateLayout.vue
cmd/wallet-web/src/layouts/OIDCLayout.vue
cmd/wallet-web/src/pages/OIDCSavePage.vue

closes #1619
https://user-images.githubusercontent.com/7862595/170584829-c90c8a83-9a27-4b6b-b1b0-21453270a236.mp4

fix: [oidc4vci] web wallet view - fix OIDC router

---

cmd/wallet-web/src/router/routes.js

closes #1687
https://user-images.githubusercontent.com/7862595/171491432-686d7ecf-ee6c-412f-a73f-7f1adf9cb0cb.mov

fix: Handle parent path of OIDC flow

---

test/ui-automation/package-lock.json
test/ui-automation/package.json

chore: removed unused deps

---

cmd/wallet-web/src/layouts/OIDCInitiateLayout.vue
cmd/wallet-web/src/layouts/OIDCLayout.vue
cmd/wallet-web/src/pages/CHAPISharePage.vue

fix: added missing import

---

cmd/wallet-web/src/layouts/GetLayout.vue
cmd/wallet-web/src/mixins/get/getCredentialsByQuery.js
cmd/wallet-web/src/pages/CHAPISharePage.vue

Likely related to https://github.com/trustbloc/sandbox/issues/1371
https://user-images.githubusercontent.com/33902374/172457590-ac1430d4-2978-4de0-8446-b8aa58faeb87.mov

fix: fixed issues in CHAPI share page

---

cmd/wallet-web/src/mixins/gnap/gnap.js
cmd/wallet-web/src/mixins/index.js
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/user.js

feat: Initiate Gnap flow for wallet integration

---

cmd/wallet-web/src/pages/CredentialsPage.vue
cmd/wallet-web/src/translations/CredentialDetails/fr.json

Closes #1350 
Credential Details Page after change:
https://user-images.githubusercontent.com/44453261/173065207-cbeb4eae-216c-4ff7-ba2b-0bb8e15f763d.mov

fix: vault filter flyout button text to be reactive

---

test/ui-automation/test/helpers/chapi.js

fix: updated automation test script

---

cmd/wallet-web/src/components/SkeletonLoader/CredentialDetailsBannerSkeletonComponent.vue
cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
cmd/wallet-web/src/components/SkeletonLoader/VerifiedInformationSkeletonComponent.vue
cmd/wallet-web/src/layouts/DashboardLayout.vue
cmd/wallet-web/src/pages/CredentialDetailsPage.vue

Closes #1667 
- Added a loading state as per designs found [here](https://app.abstract.com/projects/9ec92568-60a2-4fee-8215-5aa997d52428/branches/dc10bcee-d9a1-44f9-b644-8f843c6f1a19/commits/68d43e7308faabf1b365be94685d85413c7ad001/files/95d5757f-f10e-43f6-ad50-0faa236217fd/layers/9140877C-364A-44F4-883E-949D5F4DE3A4?collectionId=84dc8bfa-58a9-4a7b-a4a9-0bb25852746b&collectionLayerId=17a9a781-819d-4bf8-bbba-39b1237105b6&mode=build&selected=root-93118E88-6EC8-475F-B36A-1425D4DA6DA4)
https://user-images.githubusercontent.com/44453261/174147831-7558f015-6f36-4481-a63d-271ab90609db.mov
https://user-images.githubusercontent.com/44453261/174148352-9b5a5de5-f449-4d55-a3c7-166cb64b57de.mov
Mobile:
https://user-images.githubusercontent.com/44453261/174349886-3150c699-c135-44e4-b998-f6fb2f4b77f5.mov …

fix: added skeleton loader for credential details page to fix screen alignment issue

---

cmd/wallet-web/src/mixins/gnap/gnap.js
cmd/wallet-web/src/mixins/gnap/store.js
cmd/wallet-web/src/mixins/index.js
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/user.js

feat: Create gnap key pair once per session

---

cmd/wallet-server/go.mod
cmd/wallet-server/go.sum
go.mod
go.sum

Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>

chore: update afgo version.

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>

chore: update agent sdk.

---

cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/user.js
test/fixtures/wallet-web/.env

feat: added gnap access token and subjectId to agent opts

---

cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue
cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/user.js

fix: fixed navigation guard issue

---

cmd/wallet-web/src/pages/VaultsPage.vue

Closes #1747 
https://user-images.githubusercontent.com/44453261/176237976-01d9568b-5f8b-4282-935d-064bb5042b2a.mov
Also verified that closing the welcome banner, signing off, signing back with same user opens the vaults page with the welcome banner closed.

refactor: VaultsPage to use setup script

---

test/fixtures/wallet-web/.env
test/fixtures/wallet-web/docker-compose-server.yml

chore: edv image update

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json

chore: agent-sdk update

---

test/fixtures/wallet-web/hydra-config/demo_hydra_configure.sh
test/fixtures/wallet-web/oidc-config/demo_providers.yaml
test/ui-automation/test/helpers/wallet.js

fix: Update provider file to use only gnap provider

---

cmd/wallet-web/src/mixins/gnap/gnap.js
cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/options.js
cmd/wallet-web/src/store/modules/user.js

fix: addressing comments for gnap integration and cleanup

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/mixins/gnap/store.js

fix: Update wallet with latest agent-sdk change

---

test/fixtures/wallet-web/.env

chore: update to latest auth

---

test/fixtures/wallet-web/.env

Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>

chore: auth image update

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/mixins/gnap/gnap.js
cmd/wallet-web/src/mixins/gnap/store.js
cmd/wallet-web/src/router/index.js

Related to https://github.com/trustbloc/agent-sdk/issues/348

feat: integrated wallet-sdk http signature logic

---

test/fixtures/wallet-web/.env

chore: updated to latest auth

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/fixtures/wallet-web/.env
test/fixtures/wallet-web/docker-compose-server.yml

chore: enable httpsig for gnap auth and edv

---

test/fixtures/wallet-web/.env

chore: update auth

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/mixins/common/register.js
test/fixtures/wallet-web/.env
test/mock/adapter/go.mod
test/mock/adapter/go.sum
test/ui-automation/test/specs/waci-flow.js

fix: register with mediator for didcomm v1, fixing WACI DIDComm V1 tests

---

cmd/wallet-web/src/router/index.js
cmd/wallet-web/src/store/modules/user.js
test/ui-automation/test/helpers/wallet.js

Closes #1810 
Redirect to Credentials page:
https://user-images.githubusercontent.com/44453261/185851525-03671ea7-6884-4345-a45b-b5205abc8e83.mov
Redirect to WACI page after sign in in the WACI issuance flow:
https://user-images.githubusercontent.com/44453261/185923006-bdafc201-52d7-464f-82ed-d7449af16a1c.mov

fix: redirect user to correct page upon signin

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
test/ui-automation/wdio.shared.conf.js

chore: upgraded vue-i18n

---

scripts/wallet_web_start.sh
test/fixtures/wallet-web/.env
test/fixtures/wallet-web/docker-compose-server.yml

feat: pick mysql image based on architecture type

---

scripts/wallet_web_start.sh
test/fixtures/wallet-web/.env
test/fixtures/wallet-web/docker-compose-server.yml

refactor: remove manual check for arch since mysql supports both by default now

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/mixins/common/helper.js
cmd/wallet-web/src/mixins/get/didConn.js
cmd/wallet-web/src/pages/CHAPISharePage.vue
cmd/wallet-web/src/pages/MultipleQueryPage.vue
cmd/wallet-web/src/pages/StorePage.vue
cmd/wallet-web/src/pages/WACIIssuePage.vue
test/fixtures/wallet-web/static/contexts/ld-contexts.json
test/mock/adapter/adapter.go
test/mock/adapter/templates/issuer/waci-issuer.html
test/ui-automation/wdio.shared.conf.js

Also re-enabled WACI tests now that the renaming is complete
closes #1868

feat: Update agent-sdk, rename Cred Fulfillment to Cred Response

---

.github/workflows/build.yml
Makefile
docs/build.md
scripts/run_vcwallet_ui_automation.sh
scripts/run_wallet_ui_automation.sh
test/fixtures/wallet-web/docker-compose-web.yml
test/ui-automation/package-lock.json
test/ui-automation/package.json
test/ui-automation/test/helpers/chapi.js
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/credential-interaction-flow.js
test/ui-automation/test/specs/oidc-flow.js
test/ui-automation/test/specs/vault-interaction-flow.js
test/ui-automation/test/specs/waci-flow.js
test/ui-automation/wdio.conf.vcwallet.js
test/ui-automation/wdio.conf.wallet.js
test/ui-automation/wdio.shared.conf.js

test: updated configs to run both vc wallet and regular wallet instances

---

test/mock/adapter/adapter.go
test/mock/adapter/templates/verifier/oidc-verifier.html
test/ui-automation/test/specs/oidc-flow.js

Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>

test: [oidc-presentation-test] validate vc-type 

---

.github/workflows/build.yml

fix: updated publish requirements for main branch

---

cmd/wallet-web/src/components/DIDManagement/DIDPreferencesComponent.vue
cmd/wallet-web/src/mixins/common/register.js
test/ui-automation/test/helpers/wallet.js
test/ui-automation/test/specs/oidc-flow.js

feat: preference UI for selecting to request and present as either JWT/LDP

---

test/ui-automation/package-lock.json
test/ui-automation/package.json

chore: updated chromedriver to latest

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/OpenID4VCSharePage.vue
test/mock/adapter/adapter.go
test/mock/adapter/templates/verifier/openid4vc-verifier.html

Fixes #1918
https://user-images.githubusercontent.com/33902374/203879538-ec348393-ca1c-499d-9acd-7f620df8f806.mov

feat: integrated submit openid4vp api with wallet & mock verifier 

---

test/ui-automation/test/specs/openid4vc-flow.js
test/ui-automation/wdio.conf.vcwallet.js
test/ui-automation/wdio.conf.wallet.js

test: added automation tests for openid4vp flow

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/pages/OpenID4VCSharePage.vue
test/mock/adapter/adapter.go

feat: integrated JWT signing into mock openid4ci verifier 

---

test/mock/adapter/adapter.go

feat: integrated signature verification into openid4ci verifier

---

cmd/wallet-web/src/layouts/OpenID4VCLayout.vue
cmd/wallet-web/src/layouts/OpenID4VCSaveLayout.vue
cmd/wallet-web/src/pages/InitiateProtocolPage.vue
cmd/wallet-web/src/pages/OpenID4VCSavePage.vue
cmd/wallet-web/src/pages/OpenID4VCSharePage.vue
cmd/wallet-web/src/router/routes.js

feat: implementing file structure, route and UI for openid4ci pre-auth flow

---

cmd/wallet-web/package-lock.json
cmd/wallet-web/package.json
cmd/wallet-web/src/config/credential-output-descriptors.json
cmd/wallet-web/src/pages/OpenID4VCSavePage.vue
test/fixtures/wallet-web/static/config/credential-output-descriptors.json

Fixes #1948
https://user-images.githubusercontent.com/33902374/212988800-2da8af2e-9666-42ac-8761-c90619b41f74.mov

feat(ui): resolving credential for the ui and savong with openid4ci
